// The project workspace — a canvas of widgets on a constrained grid (ADR-0024).
// Today every widget is tier 0: generated by the host from journal projections
// and session state. Tier 1 (a provider's declared view schema) and tier 2 (a
// sandboxed provider view, ADR-0020) plug into the same slots without moving
// the layout, which is why the grid and the widget contract exist now.

import type { FeedEvent, ProjectRow, TerminalSession } from '../../shared/types'
import { Button, EmptyState, Panel, Row, StateChip } from './components'
import { sessionTone } from './sessionTone'
import { StopStatus } from './SessionStop'
import { useT } from './i18n'
import { runnerLabel } from './runnerLabel'

const LAYOUT_REVISION = 1

export function Workspace({
  project,
  sessions,
  feed,
  onBack
}: {
  project: ProjectRow
  /** Null until read (M108). Filtering a list you have NOT read leaves it
   *  unread — null in, null out — so a panel cannot mistake "no rows for this
   *  project" for "no answer yet". */
  sessions: TerminalSession[] | null
  feed: FeedEvent[] | null
  onBack: () => void
}): React.JSX.Element {
  const t = useT()

  const widgets = [
    {
      id: 'agents',
      title: t('workspace.agents'),
      span: 1 as const,
      tier: 0,
      body: (
        <div className="widget-list">
          {(sessions?.length ?? 0) === 0 && (
            <EmptyState read={sessions !== null} waiting={t('workspace.reading')}>
              {t('workspace.nothingRunning')}
            </EmptyState>
          )}
          {(sessions ?? []).map((s) => (
            <Row
              key={s.sessionId}
              lead={
                <>{s.termination ? <StopStatus state={s.termination} /> : <StateChip tone={sessionTone(s.state)} dot>
                  {t(`session.state.${s.state}`)}
                </StateChip>}</>
              }
              trail={s.tail || t('agents.noOutput')}
            >
              {runnerLabel(s.optionId, t)}
            </Row>
          ))}
        </div>
      )
    },
    {
      id: 'activity',
      title: t('workspace.activity'),
      span: 1 as const,
      tier: 0,
      body: (
        <div className="widget-list">
          {(feed?.length ?? 0) === 0 && (
            <EmptyState read={feed !== null} waiting={t('workspace.reading')}>
              {t('workspace.noEvents')}
            </EmptyState>
          )}
          {[...(feed ?? [])]
            .reverse()
            .slice(0, 12)
            .map((e) => (
              <Row key={e.seq} lead={`#${e.seq}`}>
                {e.type}
              </Row>
            ))}
        </div>
      )
    },
    {
      id: 'results',
      title: t('workspace.results'),
      span: 2 as const,
      tier: 0,
      body: <EmptyState read>{t('workspace.resultsBody')}</EmptyState>
    }
  ]

  return (
    <div className="workspace">
      <header className="workspace-head">
        <Button tone="ghost" onClick={onBack}>
          {t('workspace.back', { project: project.name })}
        </Button>
        <h1>{t('workspace.title')}</h1>
        <span className="muted">{t('workspace.layoutRevision', { n: LAYOUT_REVISION })}</span>
      </header>
      <div className="canvas-grid">
        {widgets.map((w) => (
          <Panel
            key={w.id}
            quiet
            wide={w.span === 2}
            title={w.title}
            actions={<span className="muted mono">{t('workspace.tier', { n: w.tier })}</span>}
          >
            {w.body}
          </Panel>
        ))}
      </div>
    </div>
  )
}
