import {resolveFabricAttachments} from './context-items.mjs'
import {classifyFabricIntent} from './concierge.mjs'
// Target conversation UI. Memory belongs to this preview; no model or microphone is called.
const ce = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const cb=(text,action,extra='')=>`<button class="button" type="button" data-ceo-action="${action}" ${extra}>${ce(text)}</button>`
const cl=(text,view,params={})=>`<a class="button" href="#view-${view}?${ce(new URLSearchParams(params))}">${ce(text)}</a>`
export function createAssistantStore(){return {open:false,threads:new Map(),name:'Fabric',status:'ready',context:null,sequence:0}}
export function assistantScope(view,state,fixtures){
 const globals=['estate','estate-agents','inbox','profile','settings','estate-settings','usage','diagnostics','notifications','launch-home','launch-map','launch-persona','launch-start','launch-help','launch-design'];
 const global=globals.includes(view)||['manager','launch-board','launch-plan','launch-pulse','launch-releases'].includes(view)&&state.scope!=='project'||state.cohort==='new'&&!state.created;
 const estate=state.estate||'team-estate',project=global?null:fixtures.projects.find(p=>p.id===state.project&&!p.purged),task=!global&&['task','run','launch','launch-agent','context-pack'].includes(view)?state.task||(view==='launch-agent'?'CTX-AT-42':null):null;
 return {key:estate+'|'+(global?'estate':state.project||'unassigned'),estate,project:project?.id||null,label:global?fixtures.estate:project?.name||'Проект недоступен',task,agent:view==='launch-agent'?'claude-code':state.agent||null,run:task?state.run||null:null,view,allowed:state.state!=='denied'&&(global||!!project),provider:state.managerSwitched?state.selectedManager||'fabric':'fabric',projects:fixtures.projects.filter(p=>!p.archived&&!p.purged).map(p=>({id:p.id,name:p.name})),paused:!!state.managerPaused,readOnly:state.phase==='read-only'||['partial','conflict','error','loading'].includes(state.state)}
}
export function assistantThread(store,key){if(!store.threads.has(key))store.threads.set(key,{id:'conversation-'+(++store.sequence),draft:'',messages:[],proposals:[],sequence:0,kind:'task',voice:{phase:'idle'},notice:'',attachments:[],contextQuery:'',contextPicker:false});return store.threads.get(key)}
export function submitAssistantMessage(store,context){
 const t=assistantThread(store,context.key),text=t.draft.trim();if(!text||['recording','processing'].includes(t.voice.phase)||!context.allowed||context.readOnly||['thinking','unavailable','error'].includes(store.status))return null;
 const attached=resolveFabricAttachments(t.attachments||[],context.items||[]);if(!attached.ok){t.notice=attached.error;return null}
 const id=t.id+':message-'+(++t.sequence),at=new Date().toISOString(),origin={estate:context.estate,project:context.project,task:context.task,agent:context.agent,run:context.run};
 const message={attachments:attached.items,id,role:'user',text,at,origin,input:t.voice.phase==='review'?'voice-demo':'text',original:t.voice.original||text,revision:t.voice.original&&t.voice.original!==text?2:1};
 t.messages.push(message);t.draft='';t.attachments=[];t.contextPicker=false;t.notice='';t.voice={phase:'idle'};
 const intent=classifyFabricIntent(text,t.kind);if(['read','form','clarify'].includes(intent.mode)){t.kind='task';return {message,intent}}
 const proposal={automatic:intent.mode==='write'&&!!context.project,id:id+':proposal',requestId:id+':apply',attachments:attached.items,kind:intent.id==='unknown'?'task':intent.id,prompt:text,title:text,result:intent.id==='topic'?'Тема появится на доске выбранного проекта. Это вопрос для разбора, а не задача исполнителя.':intent.id==='agent-config'?'Откроется конфигурация с этой инструкцией. Сохранение и допуск исполнителя — отдельные действия.':intent.id==='workflow-config'?'Откроется черновик цикла на паузе. Проверьте расписание и границы перед включением.':'Задача будет записана в выбранный проект. Исполнитель сам не запустится.',project:context.project||'',scope:context.label,task:context.task||'',source:id,conversationId:t.id,messageId:id,origin,saved:false};
 if(!proposal.automatic)t.messages.push({id:id+':reply',role:'assistant',text:'Подготовлено предложение. Проверьте, куда его записать.',at,origin,input:'demo-response',revision:1});t.proposals.push(proposal);t.kind='task';return {message,proposal}
}
export async function applyAssistantProposal(store,context,id,callback){
 const t=assistantThread(store,context.key),p=t.proposals.find(x=>x.id===id);if(!p||p.saved||p.pending||!p.project||!context.allowed||context.readOnly)return null;
 p.pending=true;p.error='';try{const result=await callback({...p});if(result?.ok&&result.receipt&&result.entityRef){p.saved=true;p.receipt=result.receipt;p.entityRef=result.entityRef;t.messages.push({id:p.requestId+':receipt',role:'assistant',text:'Записано: '+result.receipt,at:new Date().toISOString(),origin:{...p.origin,project:p.project,task:p.task||null},input:'receipt',revision:1});return result}p.error=result?.error||'Запись не подтверждена. Проверьте тот же запрос; новое поручение не создаётся.';return result}catch{p.error='Исход записи неизвестен. Проверьте этот же запрос.';return null}finally{p.pending=false}
}
function voiceUI(t,context){const v=t.voice,errors={denied:'Доступ к микрофону запрещён',device:'Микрофон не найден',silence:'Речь не обнаружена',interrupted:'Запись прервана',stt:'Расшифровка недоступна'};return `<section class="ceo-voice"><div class="actions">${cb(v.phase==='recording'?'Остановить запись':'Голосовой ввод · пример',v.phase==='recording'?'voice-stop':'voice-start',v.phase==='processing'||context.readOnly?'disabled':'')}${v.phase!=='idle'?cb('Отменить','voice-cancel'):''}</div>${v.phase==='recording'?'<p role="status">● Запись в примере · область закреплена. Микрофон не включён.</p>':v.phase==='processing'?`<p role="status">Обработка записи в примере…</p>${cb('Показать расшифровку','voice-transcript')}`:v.phase==='review'?'<p role="status">Проверьте и исправьте текст ниже. Отправка — отдельное действие.</p>':errors[v.phase]?`<p role="alert">${errors[v.phase]}. Черновик сохранён; можно продолжить текстом.</p>`:''}<details><summary>Проверить ошибки голоса</summary>${Object.entries(errors).map(([id,label])=>cb(label,'voice-'+id)).join('')}</details></section>`}
function contextComposer(t,c){
 const selected=t.attachments||[],query=(t.contextQuery||'').toLowerCase(),items=(c.items||[]).filter(x=>(x.title+' '+(x.projectName||'')+' '+x.kind).toLowerCase().includes(query));
 return `<div class="ceo-context"><label><span class="sr-only">Проект разговора</span><select data-ceo-scope aria-label="Проект разговора" ${['recording','processing'].includes(t.voice.phase)?'disabled':''}><option value="" ${!c.project?'selected':''}>Без проекта · общий контекст</option>${c.projects.map(p=>`<option value="${ce(p.id)}" ${c.project===p.id?'selected':''}>${ce(p.name)}</option>`).join('')}</select></label>${cb('+ Контекст','context-picker',`aria-expanded="${!!t.contextPicker}"`)}</div>${selected.length?`<div class="ceo-attachments" aria-label="Приложенный контекст">${selected.map(x=>cb(x.kind+': '+x.title+' ×','remove-context',`data-ceo-item="${ce(x.id)}" aria-label="Убрать ${ce(x.title)} из контекста"`)).join('')}</div>`:''}${t.contextPicker?`<section class="ceo-context-picker"><label class="field">Найти проект, задачу или источник<input name="ceo-context-query" value="${ce(t.contextQuery)}" placeholder="Название или проект"></label><div class="ceo-context-results">${items.slice(0,30).map(x=>cb(x.title+' · '+(x.projectName||x.kind),'attach-context',`data-ceo-item="${ce(x.id)}" ${selected.some(a=>a.id===x.id)||selected.length>=8?'disabled':''}`)).join('')||'<p>Доступных совпадений нет.</p>'}</div><small>До 8 источников. Они не меняют проект назначения.</small>${cb('Готово','context-picker')}</section>`:''}`
}
export function renderAssistant(store,context,brand){
 const prior=store.context;store.context=context;
 if(prior&&prior.key!==context.key){const old=assistantThread(store,prior.key);if(['recording','processing'].includes(old.voice.phase)){old.voice.phase='interrupted';old.notice='Запись остановлена при смене области. Черновик остался в исходном разговоре.'}}
 const t=assistantThread(store,context.key),status=!context.allowed?'Нет доступа':context.readOnly?'Последний снимок':context.paused?'Циклы на паузе':store.status==='unavailable'?'Модель не подключена':store.status==='error'?'Связь прервана':'Готов помочь',disabled=context.readOnly||['unavailable','error','thinking'].includes(store.status);
 const proposalHTML=p=>`<section class="ceo-artifact"><span class="chip">${p.saved?'Сохранено':p.pending?'Записываем':'Проверить поручение'}</span><h4>${ce(p.title)}</h4>${p.saved?`${cl('Открыть '+(p.kind==='task'?'задачу':p.kind==='topic'?'тему':'настройку'),p.entityRef.view,p.entityRef.params)}<details><summary>Результат и источник</summary><p>${ce(p.receipt)}</p><p>${ce(p.source)} · ${ce(p.project)}</p></details>`:`<p>${ce(p.result)}</p><label class="field">Проект назначения<select data-ceo-destination="${ce(p.id)}"><option value="">Выберите проект</option>${context.projects.map(x=>`<option value="${ce(x.id)}" ${p.project===x.id?'selected':''}>${ce(x.name)}</option>`).join('')}</select></label><details><summary>Связь с исходной задачей</summary><input aria-label="Исходная задача" data-ceo-task="${ce(p.id)}" value="${ce(p.task||'')}"></details>${p.error?`<p role="alert">${ce(p.error)}</p>`:''}${cb(p.error?'Проверить запись':p.kind==='agent-config'?'Открыть черновик агента':p.kind==='workflow-config'?'Открыть черновик цикла':p.kind==='topic'?'Добавить тему':'Создать задачу','accept',`data-ceo-id="${ce(p.id)}" ${context.readOnly||!p.project||p.pending?'disabled':''}`)}${cb('Отменить','dismiss',`data-ceo-id="${ce(p.id)}" ${p.pending?'disabled':''}`)}`}${p.saved&&p.kind==='task'?`<details><summary>Уточнить связь</summary><label class="field">Связанная задача<input data-ceo-link-task="${ce(p.id)}" value="${ce(p.linkDraft??p.task??'')}"></label>${cb('Сохранить связь','save-link',`data-ceo-id="${ce(p.id)}"`)}${p.linkNotice?`<p role="status">${ce(p.linkNotice)}</p>`:''}</details>`:''}</section>`;
 const messages=t.messages.filter(m=>m.input!=='receipt'||!t.proposals.some(p=>p.requestId+':receipt'===m.id)).map(m=>`<article class="ceo-message ${m.role} ${context.message===m.id?'ceo-highlight':''}" id="${ce(m.id)}"><strong>${m.role==='user'?'Вы':'Fabric'}</strong><p>${ce(m.text)}</p>${(m.attachments||[]).length?`<details><summary>Контекст · ${m.attachments.length}</summary>${m.attachments.map(x=>cl(x.title,x.view,{...x.params,estate:context.estate})).join('')}</details>`:''}${(m.links||[]).map(l=>cl(l.label,l.view,l.params)).join('')}<details><summary>${ce(m.at.slice(11,16))} · источник</summary><p>${ce(m.id)} · ${ce(m.origin?.project||'Общий контекст')}</p><p>${m.input==='voice-demo'?'Голосовой пример · ':''}Версия ${m.revision}. ${m.original&&m.original!==m.text?'Исходная расшифровка: '+ce(m.original):''}</p></details></article>`+t.proposals.filter(p=>p.source===m.id).map(proposalHTML).join('')).join('');
 return `<button type="button" class="ceo-launcher" data-ceo-action="toggle" aria-expanded="${store.open}" aria-controls="ceo-panel" aria-label="Открыть CEO — ${ce(context.label)}">${brand}<span><strong>Fabric</strong><small>${ce(status)}</small></span><span aria-hidden="true">↗</span></button><aside id="ceo-panel" class="ceo-panel" tabindex="-1" ${store.open?'':'hidden'} aria-label="Чат Fabric"><header class="ceo-header"><div class="ceo-identity">${brand}<div><strong>Fabric</strong><p class="meta">${ce(status)}</p></div></div><div class="actions">${cl('Помощь','launch-help',{project:context.project||'',estate:context.estate})}${cb('Закрыть','close')}</div></header>${!context.allowed?'<div class="notice warning"><h3>История недоступна</h3><p>Восстановите доступ к выбранной области. Другой разговор не подставляется.</p></div>':`<div class="ceo-conversation" role="log" aria-live="polite">${messages||`<div class="ceo-welcome"><h3>${context.project?'Что продвинем в проекте?':'С чего начнём?'}</h3><p>${context.project?ce(context.label)+' · спросите о состоянии или поручите работу.':'Найдём проект, разберём доску или начнём новую работу.'}</p><div class="ceo-quick">${context.project?cb('Вернуть контекст','suggest-context'):cb('Найти проект','suggest-search')}${cb('Что требует решения','suggest-board')}${cb('Поручить работу','suggest-goal')}</div></div>`}</div>${t.notice?`<p class="ceo-inline-notice" role="status">${ce(t.notice)}</p>`:''}${disabled?`<div class="ceo-inline-notice" role="status">${ce(status)}. Черновик сохранён. ${store.status==='error'?cb('Повторить','retry'):''}</div>`:''}<form data-ceo-form="chat" class="ceo-composer">${contextComposer(t,context)}<label class="field"><span class="sr-only">Сообщение Fabric</span><textarea name="ceo-message" aria-label="Сообщение Fabric" rows="3" placeholder="Спросите или поручите…">${ce(t.draft)}</textarea></label>${t.voice.phase!=='idle'?voiceUI(t,context):''}<div class="actions"><details class="ceo-tools"><summary>Ещё</summary>${cb('Настроить агента','suggest-agent')}${cb('Настроить цикл','suggest-workflow')}${cl('Полномочия','manager',{scope:context.project?'project':'estate',estate:context.estate,...(context.project?{project:context.project}:{})})}<p>Уровень знакомства не меняет полномочия. Журнал хранится до перезагрузки макета.</p></details><div class="actions">${t.voice.phase==='idle'?cb('Голос','voice-start',disabled?'disabled':''):''}<button class="button primary" type="submit" ${disabled||['recording','processing'].includes(t.voice.phase)?'disabled':''}>Отправить</button></div></div><small class="ceo-demo-label">Пример · без модели и микрофона</small></form><details class="ceo-debug"><summary>Проверить состояния макета</summary>${cb('Модель недоступна','unavailable')}${cb('Обрыв соединения','failure')}${cb('Без результата','no-result')}${cb('Восстановить пример','available')}<p>Журнал · ${t.messages.length} записей · ${ce(t.id)}</p></details>`}</aside>`
}
export function attachAssistant(host,store,options={}){
 const draw=()=>{host.innerHTML=renderAssistant(store,options.context(),typeof options.brand==='function'?options.brand():options.brand);document.querySelector('.workbench')?.classList.toggle('ceo-open',store.open);host.classList.toggle('ceo-is-open',store.open);const modal=store.open&&window.matchMedia('(max-width:600px)').matches;const panel=host.querySelector('#ceo-panel');panel?.setAttribute('role',modal?'dialog':'complementary');if(modal)panel?.setAttribute('aria-modal','true');for(const el of document.querySelectorAll('.app-main,.app-sidebar'))el.inert=modal;document.body.classList.toggle('ceo-modal',modal)};
 host.addEventListener('input',e=>{const t=assistantThread(store,store.context.key);if(e.target.name==='ceo-message')t.draft=e.target.value;if(e.target.name==='ceo-context-query'){t.contextQuery=e.target.value;draw();host.querySelector('[name=ceo-context-query]')?.focus()}if(e.target.dataset.ceoLinkTask){const p=t.proposals.find(p=>p.id===e.target.dataset.ceoLinkTask);if(p)p.linkDraft=e.target.value.trim()}if(e.target.dataset.ceoTask){const p=t.proposals.find(p=>p.id===e.target.dataset.ceoTask);if(p&&!p.saved)p.task=e.target.value.trim()}});
 host.addEventListener('change',e=>{if(e.target.matches('[data-ceo-scope]')){if(['recording','processing'].includes(assistantThread(store,store.context.key).voice.phase)){draw();return}options.onScope?.(e.target.value);return;}if(e.target.dataset.ceoDestination){const p=assistantThread(store,store.context.key).proposals.find(p=>p.id===e.target.dataset.ceoDestination);if(p&&!p.saved&&!p.pending){p.project=e.target.value;p.task='';draw()}}});
 host.addEventListener('submit',async e=>{if(!e.target.dataset.ceoForm)return;e.preventDefault();const context={...store.context},out=submitAssistantMessage(store,context);if(out){options.onMessage?.(out.message);if(out.intent){const result=options.onRead?.(out.intent,out.message.text,context)||{text:'Этот запрос доступен через руководство.',links:[]};const reply={id:out.message.id+':reply',role:'assistant',at:new Date().toISOString(),origin:out.message.origin,input:'demo-response',revision:1,...result};assistantThread(store,context.key).messages.push(reply);options.onMessage?.(reply)}else if(out.proposal?.automatic){const pending=applyAssistantProposal(store,context,out.proposal.id,options.onArtifact);draw();await pending}}draw();host.querySelector('textarea')?.focus()});
 host.addEventListener('click',async e=>{
  const b=e.target.closest('[data-ceo-action]');if(!b||b.disabled)return;const a=b.dataset.ceoAction,t=assistantThread(store,store.context.key);
  if(a==='toggle'||a==='close'){if(a==='close'&&['recording','processing'].includes(t.voice.phase))t.voice.phase='interrupted';store.open=a==='toggle'?!store.open:false;draw();host.querySelector(store.open?'textarea':'.ceo-launcher')?.focus();return}
  if(!store.context.allowed)return;
  if(a==='context-picker')t.contextPicker=!t.contextPicker;
  if(a==='attach-context'){const item=store.context.items?.find(x=>x.id===b.dataset.ceoItem);t.attachments??=[];if(item&&t.attachments.length<8&&!t.attachments.some(x=>x.id===item.id))t.attachments.push(structuredClone(item))}
  if(a==='remove-context')t.attachments=t.attachments.filter(x=>x.id!==b.dataset.ceoItem);
  if(a==='accept'){const context={...store.context};const pending=applyAssistantProposal(store,context,b.dataset.ceoId,options.onArtifact);draw();await pending;draw();return}
  if(a==='save-link'){const p=t.proposals.find(p=>p.id===b.dataset.ceoId);if(p&&!store.context.readOnly){const result=options.onRelink?.(p,p.linkDraft??p.task??'');if(result?.ok){p.task=p.linkDraft??p.task??'';p.linkNotice='Связь записана: '+result.receipt;t.messages.push({id:result.receipt,role:'assistant',text:'Связь уточнена: '+(p.task||'без задачи'),at:new Date().toISOString(),origin:{...p.origin,project:p.project,task:p.task},input:'receipt',revision:1})}else p.linkNotice=result?.error||'Связь не сохранена'}}
  if(a==='dismiss')t.proposals=t.proposals.filter(p=>p.id!==b.dataset.ceoId||p.pending);
  if(a.startsWith('suggest-')){t.kind=a==='suggest-agent'?'agent-config':a==='suggest-workflow'?'workflow-config':'task';t.draft={'suggest-search':'Покажи список проектов','suggest-context':'Собери изменения с прошлого визита','suggest-board':'Что требует моего решения на доске?','suggest-agent':'Reviewer: проверять результат по критериям и ссылкам на источники.','suggest-workflow':'Утренний обзор: собрать изменения и вопросы, требующие моего решения.','suggest-goal':'Создай задачу: проверить первый полезный результат.'}[a]||''}
  if(a==='voice-start'&&!store.context.readOnly){t.voice={phase:'recording',scope:{...store.context},previous:t.draft}}
  if(a==='voice-stop')t.voice.phase='processing';
  if(a==='voice-transcript'){t.voice.phase='review';t.voice.original='Собери изменения с прошлого визита и вынеси вопросы на доску.';t.draft=t.voice.original}
  if(a==='voice-cancel'){t.draft=t.voice.previous??t.draft;t.voice={phase:'idle'}}
  if(['denied','device','silence','interrupted','stt'].some(x=>a==='voice-'+x))t.voice.phase=a.slice(6);
  if(a==='no-result'){const m={id:t.id+':message-'+(++t.sequence),role:'assistant',text:'Результат не получен. Уточните поручение или запишите задачу вручную.',at:new Date().toISOString(),origin:{estate:store.context.estate,project:store.context.project,task:store.context.task},input:'demo-response',revision:1};t.messages.push(m);options.onMessage?.(m)}
  if(a==='unavailable')store.status='unavailable';if(a==='failure')store.status='error';if(['available','retry'].includes(a))store.status='ready';
  draw();if(a.startsWith('suggest-')||a==='voice-transcript')host.querySelector('textarea')?.focus()
 });
 host.addEventListener('keydown',e=>{if(e.key==='Tab'&&store.open&&window.matchMedia('(max-width:600px)').matches){const items=[...host.querySelectorAll('#ceo-panel button:not([disabled]),#ceo-panel select,#ceo-panel input,#ceo-panel textarea,#ceo-panel a[href],#ceo-panel summary')].filter(x=>x.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}if(e.key==='Escape'&&store.open){const t=assistantThread(store,store.context.key);if(['recording','processing'].includes(t.voice.phase))t.voice.phase='interrupted';store.open=false;draw();host.querySelector('.ceo-launcher')?.focus();e.stopPropagation()}});
 window.matchMedia('(max-width:600px)').addEventListener('change',()=>{if(store.open)draw()});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&store.open&&!host.contains(e.target)){store.open=false;draw();host.querySelector('.ceo-launcher')?.focus()}});
 return {render:draw}
}
