const cx=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const calmFamilies=[
 {id:'orientation',title:'Вернуться в контекст',views:['r0-home','ceo-conversation','r0-project','r0-map','estate','launch-home','project','launch-project','launch-pulse','launch-releases','profile','launch-persona','inbox','launch-map','launch-design'],first:'Приоритет, последнее изменение и следующий шаг',detail:'История, метрики и подтверждающие источники',criterion:'Найти требующий внимания объект и перейти к нему без чтения всей ленты.'},
 {id:'decision',title:'Принять решение',views:['r0-board','board','launch-board','question','authority','reports','proposal','cross-project-proposal','decisions'],first:'Вопрос, причина, последствия и доступный ответ',detail:'Обсуждение, версии и квитанция',criterion:'Записать решение один раз; видеть отказ или ожидание передачи.'},
 {id:'execution',title:'Довести работу до результата',views:['r0-work','task-new','launch','task','run','agents','estate-agents','agent-detail','launch-agent','task-archive','schedule','cycles','routine-editor','pipeline','run-trace','fabric-tools','optimizer'],first:'Ожидаемый результат, наблюдаемый статус и допустимый переход',detail:'Редактирование, конфигурация, параметры и проверка макета',criterion:'Понять, кто действует дальше; остановка и восстановление доступны в своём состоянии.'},
 {id:'planning',title:'Понять направление',views:['r0-plan','agent-history','project-history','project-plan','launch-plan','goals','goal','retro','feedback'],first:'Цель, выбранный объект и ближайшие зависимости',detail:'Происхождение связей, версии, история',criterion:'Раскрыть состав, открыть точный объект и вернуться; факт отделён от плана.'},
 {id:'setup',title:'Настроить работу',views:['r0-provider','r0-settings','providers','manager','admission','bootstrap','connections','connect-account','access','access-detail','mcp-servers','agent-access','project-settings','role-workspace','membership','invite','workspace-editor','harness','harness-tool','usage','estate-settings','settings','notifications','provider-accounts','account-switch'],first:'Область, действующая конфигурация и следующий шаг готовности',detail:'Дополнительные источники, версии, история и диагностика',criterion:'Изменить конкретные параметры и увидеть результат; допуск не подразумевается выбором.'},
 {id:'sources',title:'Изучить источники и восстановиться',views:['r0-memory','memory','context-pack','memory-lineage','sync','restore','private-history','workspace','editor','session','search','support','release','content','diagnostics','archive','service-terminal','internal-browser','media-preview','file-diff','document'],first:'Адресный объект, свежесть и доступное действие',detail:'Содержимое, исходные события, технические основания',criterion:'Отличить отсутствие данных от ошибки/нет доступа; восстановиться без чужого контекста.'},
 {id:'adoption',title:'Начать и освоиться',views:['first-run','start-add','start-scan','start-new','start-agent','start-convert','r0-setup','r0-source','r0-discovery','r0-guide','onboarding','launch-start','launch-guide','launch-help','landing'],first:'Один полезный шаг и понятный результат',detail:'Полный маршрут, дополнительные примеры и настройки',criterion:'Получить первый результат до полного сетапа; пропуск не засчитывается как выполнение.'}
];
export function calmFamily(view){return calmFamilies.find(f=>f.views.includes(view))}
export function renderCalmAtlas(state,model){
 const head='<header class="page-title"><div><p class="eyebrow">Карта интерфейса</p><h2 tabindex="-1">Главное сразу. Детали — рядом.</h2><p>Выберите задачу оператора, изучите устройство экрана и откройте его макет.</p></div></header>';
 if(state.state==='denied')return head+'<section class="panel"><h3>Нет доступа</h3><p>Содержимое скрыто. Вернитесь в доступную область.</p><a class="button" href="#view-launch-home?state=ready">К Fabric</a></section>';
 if(['error','loading','partial','conflict'].includes(state.state))return head+'<section class="panel"><h3>Состояние карты не подтверждено</h3><p>Перечитайте источник перед изучением состава.</p><a class="button" href="#view-launch-design?state=ready">Перечитать карту</a></section>';
 if(state.state==='empty')return head+'<section class="panel"><p>Начните с главной и выберите нужный рабочий сценарий.</p><a class="button" href="#view-launch-home?state=ready">Открыть Fabric</a></section>';
 return head+`<section class="calm-principles"><div><b>01 · Ориентироваться</b><p>Где я, что изменилось, что требует меня.</p></div><div><b>02 · Действовать</b><p>Один следующий шаг и понятный результат.</p></div><div><b>03 · Разобраться</b><p>Детали, связи и история по запросу.</p></div></section><div class="calm-filter"><label class="field">Найти экран<input data-calm-search placeholder="Например: задача, настройка, контекст"></label><label class="field">Задача оператора<select data-calm-family><option value="">Все задачи</option>${calmFamilies.map(f=>`<option value="${f.id}">${cx(f.title)}</option>`).join('')}</select></label></div><p class="meta" data-calm-count>${model.views.length} представлений · target design</p><div class="calm-atlas">${model.views.map(v=>{const f=calmFamily(v.id);return `<article class="panel calm-screen" data-calm-card data-family="${f?.id||''}" data-search="${cx(v.title+' '+v.id+' '+(f?.title||''))}"><span class="chip">${cx(f?.title||'Обзор')}</span><h3>${cx(v.title)}</h3><p>${cx(v.purpose||v.title)}</p><a class="button" href="#view-${v.id}?state=ready&project=${cx(state.project||'atlas')}&estate=${cx(state.estate||'team-estate')}">Открыть макет →</a><details><summary>Композиция и приёмка</summary><dl><dt>Сразу</dt><dd>${cx(f?.first)}</dd><dt>При раскрытии</dt><dd>${cx(f?.detail)}</dd><dt>Проверить</dt><dd>${cx(f?.criterion)}</dd></dl><p>Пусто, чтение, ошибка, нет доступа, последний снимок и конфликт проверяются переключателем над макетом.</p><small>${cx(v.screen_ids.join(' · '))} · ${cx(v.id)}</small></details></article>`}).join('')}</div>`
}
export function renderCalmNav(view,state,model,fixtures){
 const params=id=>new URLSearchParams({estate:state.estate||'team-estate',project:state.project||'',state:'ready',...(['launch-home','launch-board','launch-plan','launch-design'].includes(id)?{scope:'estate'}:{})});
 const link=(id,title)=>`<a href="#view-${id}?${cx(params(id))}" ${view===id?'class="current" aria-current="page"':''}>${cx(title)}</a>`;
 const p=fixtures.projects.find(p=>p.id===state.project),projectViews=['launch-project','launch-agent','agents','cycles','goals','memory','project-settings'];
 return `<label class="mobile-app-nav field">Раздел<select id="mobile-app-view">${calmFamilies.map(f=>`<optgroup label="${cx(f.title)}">${model.views.filter(v=>f.views.includes(v.id)).map(v=>`<option value="${v.id}" ${v.id===view?'selected':''}>${cx(v.title)}</option>`).join('')}</optgroup>`).join('')}</select></label><div class="calm-main-nav">${link('launch-home','Fabric')}${link('launch-board','Доска')}${link('launch-plan','Планирование')}${link('launch-start','+ Проект')}</div>${p?`<details class="calm-nav-group" ${projectViews.includes(view)?'open':''}><summary>${cx(p.name)}</summary>${[['launch-project','Обзор проекта'],['agents','Команда'],['cycles','Циклы'],['goals','Цели'],['memory','Память'],['project-settings','Настройки']].map(([id,t])=>link(id,t)).join('')}</details>`:''}<details class="calm-nav-group" ${['providers','manager','provider-accounts','usage','notifications'].includes(view)?'open':''}><summary>Управление</summary>${[['providers','Настроить агента'],['manager','Полномочия Fabric'],['provider-accounts','Аккаунты ИИ'],['usage','Квоты'],['notifications','Уведомления']].map(([id,t])=>link(id,t)).join('')}</details><details class="calm-nav-group"><summary>Все разделы · ${model.views.length}</summary><div class="calm-all-nav">${calmFamilies.map(f=>`<p class="app-nav-label">${cx(f.title)}</p>${model.views.filter(v=>f.views.includes(v.id)).map(v=>link(v.id,v.title)).join('')}`).join('')}</div></details><div class="calm-help-nav">${link('launch-help','Помощь Fabric')}${link('launch-design','Карта интерфейса')}</div>`
}
export function attachCalmAtlas(host){const filter=()=>{const q=(host.querySelector('[data-calm-search]')?.value||'').toLowerCase(),family=host.querySelector('[data-calm-family]')?.value||'';let count=0;for(const card of host.querySelectorAll('[data-calm-card]')){card.hidden=!!(family&&card.dataset.family!==family||!card.dataset.search.toLowerCase().includes(q));if(!card.hidden)count++}const counter=host.querySelector('[data-calm-count]');if(counter)counter.textContent=count?count+' представлений · target design':'Совпадений нет. Измените запрос или выберите все задачи.'};host.addEventListener('input',e=>{if(e.target.matches('[data-calm-search]'))filter()});host.addEventListener('change',e=>{if(e.target.matches('[data-calm-family]'))filter()})}
