import {folderPickerControl} from './folder-picker.mjs'
import {creationRecord,creationRoute,creationList,discardCreation,normalizedCreation,updateCreation,reviewCreation,commitCreation,pendCreation,reconcileCreation} from './new-project.mjs'
import {fabricCapabilities} from './concierge.mjs'
// Guided target design: user-entered project data, page-local receipts, explicitly simulated discovery.
const ge=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const gl=(label,view,params={})=>`<a class="button" href="#view-${view}?${ge(new URLSearchParams(params))}">${ge(label)}</a>`;
const gb=(label,action,extra='')=>`<button class="button" type="button" data-guide="${action}" ${extra}>${ge(label)}</button>`;
const gf=(label,name,value='')=>`<label class="field">${ge(label)}<input data-guide-field="${name}" value="${ge(value)}"></label>`;
export const guideRecords=new Map();
export const guidedViews=['onboarding','launch-start','launch-guide','launch-help'];
export function guideRecord(state){
 if(state.guideView!=='launch-guide')return creationRecord(state)
 const key=(state.estate||'team-estate')+'|'+(state.guideProject||state.project)+'|v1'
 if(!guideRecords.has(key))guideRecords.set(key,{key,completed:[],notice:''})
 return guideRecords.get(key)
}
const guideSteps=['Источник','Первый результат','Проверка'];
export function renderGuided(view,state,fixtures){if(!guidedViews.includes(view))return null;view=creationRoute(view);
 const g=guideRecord({...state,guideView:view}),estate=state.estate||'team-estate',params={estate,project:state.project,...(g.draftId?{draftId:g.draftId}:{})},kind=state.phase==='read-only'?'read-only':state.state||'ready';
 const head=`<header class="page-title"><div><p class="eyebrow">Fabric · знакомство</p><h2 tabindex="-1">${view==='launch-start'?'Начнём с вашего проекта':view==='launch-guide'?'Первый полезный результат':'Как работать с Fabric'}</h2><p>Один следующий шаг. Остальное — когда понадобится.</p></div>${gl('Вернуться к работе','launch-home',params)}</header>`;
 if(kind==='read-only')return head+'<section class="panel"><h3>Снимок доступен только для чтения.</h3>'+gl('Вернуться к работе','launch-home',params)+'</section>';
 if(kind==='denied')return head+'<section class="panel"><h3>Нет доступа</h3><p>Содержимое проекта скрыто. Обучение не расширяет полномочия.</p>'+gl('Выбрать пространство','membership',{estate})+'</section>';
 if(!['ready','empty'].includes(kind))return head+`<section class="panel"><h3>${kind==='loading'?'Читаем состояние':kind==='error'?'Источник не ответил':'Нужно обновить состояние'}</h3><p>Черновик сохранён. Создание проекта и задачи удержано до подтверждения состояния.</p>${gl('Перечитать',view,{...params,state:'ready'})}</section>`;
 if(kind==='empty')return head+'<section class="panel"><h3>Начните с первого проекта</h3><p>Выберите папку, отдельный проект или идею. История появится после ваших действий.</p>'+gl('Начать знакомство','launch-start',{...params,state:'ready'})+'</section>';
 const helpProject=fixtures.projects.find(p=>p.id===state.project&&p.id!=='personal-empty'&&(p.estate||'team-estate')===estate&&!p.archived&&!p.purged);
 const draftResume=!g.project&&(g.name||g.purpose||g.repo||g.step)?gl('Продолжить черновик','launch-start',params):'';
 const helpResume=(helpProject?gl('Продолжить знакомство · '+helpProject.name,'launch-guide',{estate,project:helpProject.id}):'')+draftResume;
 let body='';
 if(view==='launch-help')body=`<section class="panel guide-intro"><h3>Fabric — ваш CEO</h3><p>Напишите, что нужно получить. Fabric найдёт контекст, запишет поручение или подготовит параметры действия. Откройте его из любого экрана кнопкой с цветным аватаром.</p><p>Область над разговором показывает, с каким проектом вы работаете. У разных проектов — разные разговоры.</p>${gb('Открыть Fabric','chat')} ${helpResume||gl('Пройти знакомство','launch-start',params)}</section><div class="guide-examples">${[
 ['Вернуться в контекст','Собери изменения с прошлого визита','Короткое состояние и переход к источникам.'],['Найти проект','Найди проект Atlas','Только доступные проекты; без новых задач.'],['Разобрать доску','Что требует моего решения на доске?','Вопросы для оператора. Задачи агентов остаются у исполнителей.'],['Поручить работу','Создай задачу: проверить вход в приложение','Запись задачи в выбранный проект. Запуск требует готового исполнителя.'],['Настроить исполнителя','Настрой агента Reviewer','Черновик инструкции; доступ и проверка отдельно.'],['Настроить ритм','Настрой цикл: утренний обзор','Черновик цикла на паузе до проверки расписания.'],['Проверить инструменты','Покажи harness и доступ','Общая форма инструментов, допусков и ограничений.'],['Остановить цикл','Поставь цикл на паузу','Открывается список циклов; выбираете конкретный и видите результат.']
 ].map(([title,prompt,body],i)=>`${i===3?'<details class="guide-more-examples"><summary>Ещё примеры поручений</summary><div class="guide-examples">':''}<article class="panel"><h3>${title}</h3><p>${body}</p>${gb(prompt,'example',`data-prompt="${ge(prompt)}"`)}</article>${i===7?'</div></details>':''}`).join('')}</div><details class="panel"><summary>Все управленческие возможности</summary><div class="guide-examples">${fabricCapabilities.map(c=>`<div><strong>${ge(c.label)}</strong><p>${c.mode==='form'?'Точные параметры и подтверждение в общей форме':'Чтение доступных данных'}</p>${gl('Открыть',c.view,params)}</div>`).join('')}</div></details><details class="panel"><summary>Голос, журнал и полномочия</summary><p>Голос → остановить → проверить расшифровку → отправить. При ошибке текст сохраняется. Исходная реплика, правки, проект и запись результата связаны в журнале.</p><p>В макете голос, ответы и сканирование демонстрационные; данные живут до перезагрузки. В продукте нужны durable journal, STT и подтверждённые adapters. Уровень знакомства не даёт новых прав. Секреты вводятся в настройках подключения.</p>${gl('Конфигурация Fabric','manager',params)}${gl('Облик и аватар','launch-persona',params)}</details>`;
 else if(view==='launch-start'&&g.project){body=`<section class="panel"><h3>Проект уже создан</h3><p>Продолжите знакомство или добавьте ещё один проект.</p>${gl('Продолжить знакомство','launch-guide',{estate,project:g.project})}${gb('Добавить другой проект','another')}</section>`}
 else if(view==='launch-start'){
 const steps=`<ol class="guide-steps">${guideSteps.map((s,i)=>`<li ${g.step===i?'aria-current="step"':''}>${i+1}. ${s}</li>`).join('')}</ol>`;
 if(g.step===0)body=`<h3>Откуда начнём?</h3><div class="guide-choices">${[['folder','Папка с проектами','Посмотреть найденное и выбрать первый'],['single','Один проект','Добавить известную папку или репозиторий'],['idea','Новая идея','Начать с результата, без репозитория']].map(([id,title,desc])=>gb(title+' · '+desc,'mode',`data-mode="${id}" aria-pressed="${g.mode===id}"`)).join('')}</div>${g.mode!=='idea'?folderPickerControl({id:g.mode==='folder'?'scanRoot':'repo',label:g.mode==='folder'?'Папка проектов':'Папка проекта',value:g.mode==='folder'?g.scanRoot:g.repo,attribute:'data-guide-field="'+(g.mode==='folder'?'scanRoot':'repo')+'"'}):'<p>Репозиторий можно подключить позже.</p>'}${g.mode==='folder'?`${gb('Посмотреть пример сканирования','scan')}<p class="meta">В этом макете файловая система не читается. Выбор пути и кандидатов — демонстрация будущего шага.</p>${g.scan!=='idle'?`<div role="status">${g.scan==='denied'?'Нет доступа. Выберите другую папку.':g.scan==='cancelled'?'Сканирование отменено. Ничего не создано.':g.scan==='empty'?'Проекты не найдены. Добавьте проект вручную.':g.scan==='partial'?'Прочитана часть папки; неизвестные пути не считаются пустыми.':'Найдены демонстрационные кандидаты. Создание — только после выбора и проверки.'}</div>${g.candidates.map(c=>gb(c.name+' · '+c.path,'candidate',`data-name="${ge(c.name)}" data-path="${ge(c.path)}"`)).join('')}`:''}<details><summary>Состояния сканирования</summary>${['denied','partial','empty','cancelled'].map(s=>gb(s,'scan-state',`data-state="${s}"`)).join('')}</details>`:''}${gb(g.mode==='folder'?'Добавить вручную':'Продолжить','next')}`;
 if(g.step===1)body=`<h3>Что должно стать лучше?</h3>${gf('Название проекта','name',g.name)}<label class="field">Первый полезный результат<textarea data-guide-field="purpose" rows="3" placeholder="Например: подготовить страницу записи на консультацию">${ge(g.purpose)}</textarea></label><p class="meta">Fabric предложит первую задачу из этого результата. Её можно изменить.</p>${creationAdvanced(g,fixtures)}${gb('Назад','back')}${gb('Проверить проект','next')}`;
 if(g.step===2&&g.review)body=`<h3>Создадим один проект</h3><dl class="guide-review"><dt>Проект</dt><dd>${ge(g.review.name)}</dd><dt>Результат</dt><dd>${ge(g.review.purpose)}</dd><dt>Источник</dt><dd>${ge(g.review?.repoMode==='none'?'Без репозитория':g.review?.repo||'Подключить позже')}</dd><dt>Исполнитель</dt><dd>${ge(g.review.provider==='later'?'Не выбран':g.review.provider)} · ещё не допущен</dd><dt>Шаблон</dt><dd>${ge(g.review.starter)}</dd><dt>Начальные этапы</dt><dd>${ge(g.review.stages.join(' → ')||'Не заданы')}</dd><dt>Наблюдаемый проект</dt><dd>${ge(g.review.target||'Не выбран')}</dd><dt>Будущие проекты</dt><dd>${g.review.futureConsent?'Включены в выбранный scope наблюдения':'Не включены'}</dd></dl><p>Ни файлы, ни репозиторий не изменяются. Агенты и циклы сами не запускаются.</p>${gb('Назад','back')}${gb('Создать проект','create')}`;
 if(g.step===2&&!g.review)body=`<h3>Проверьте проект ещё раз</h3>${gb('Назад','back')}${gb('Проверить проект','review')}`;
 if(g.pending)body=`<h3>Создание подтверждается</h3><p>Используем тот же запрос. Правки черновика не изменят его исход.</p>${gb('Проверить исход','reconcile')}`;
 body=steps+`<section class="panel guide-card">${g.notice?`<p role="alert">${ge(g.notice)}</p>${g.archive?gl('Открыть архивный проект','archive',{estate,project:g.archive}):g.duplicate?gl('Открыть проект','launch-project',{estate,project:g.duplicate}):''}`:''}${body}</section><details class="panel"><summary>Черновики проектов</summary>${creationList(estate).map(d=>gl(d.name||'Без названия','launch-start',{estate,draftId:d.draftId})).join('')}${gb('Отдельный черновик','another')}${gb('Сохранить черновик','save')}${gb('Отменить и сохранить черновик','cancel')}${gb('Удалить только этот черновик','discard')}</details><details><summary>Проверить восстановление</summary>${gb('Отказ создания','refused')}${gb('Потеря подтверждения','unknown')}</details><p class="meta">Можно уйти и вернуться к этому шагу в пределах страницы. Сохранение после перезапуска — в плане реализации.</p>`;
 }else{
 const p=fixtures.projects.find(p=>p.id===state.project&&!p.purged&&!p.archived);
 if(!p)return head+'<section class="panel"><p>Сначала создайте или выберите доступный проект.</p>'+gl('Создать проект','launch-start',{estate})+'</section>';
 const saved=g.project===p.id,task=saved?g.task:null;
 body=`<section class="panel guide-intro"><span class="chip">${ge(p.name)}</span><h3>${task?'Задача сохранена. Разберём доску.':'Fabric уже знает цель вашего проекта'}</h3><p>${ge(p.purpose)}</p>${gb('Обсудить с Fabric','chat')} ${gl('Открыть проект','launch-project',params)}</section><section class="panel guide-card"><h3>${task?'2. Вопросы для вашего внимания':'1. Первая задача'}</h3>${task?`<p>Работа записана отдельно от учебной подсказки. На доску попадают вопросы, решения и результаты, требующие внимания.</p>${gl('Открыть сохранённую задачу','task',{...params,task})}${gb(g.topic?'Открыть учебную тему':'Добавить знакомство с доской','board')}`:`<p>Запишите ожидаемый результат. Назначение и запуск доступны из задачи после настройки исполнителя.</p><label class="field">Поручение<textarea data-guide-field="firstTask" rows="3">${ge(g.firstTask||p.purpose)}</textarea></label>${gb('Записать первую задачу','task')}`}</section><details class="panel"><summary>Ваш путь · ${1+(task?1:0)+(g.topic?1:0)+(g.finished?1:0)} из 4 результатов</summary><ol><li>Проект создан: ${ge(p.name)}</li><li>${task?'Задача записана: '+ge(task):'Записать первую задачу'}</li><li>${g.topic?'Учебная тема на доске создана':'Познакомиться с доской'}</li><li>Вернуться к проекту и следующему шагу</li></ol><p>Это прогресс знакомства, а не оценка агента и не уровень доступа.</p>${gl('Настроить исполнителя','providers',params)}${gl('Все возможности Fabric','launch-help',params)}</details><div class="actions">${gb('Пропустить подсказки','skip')}${gb('Продолжить работу','complete')}</div>${g.notice?`<p role="status">${ge(g.notice)}</p>`:''}`;
 }
 return `<div class="guide">${head}${body}</div>`
}
export function attachGuided(host,options){
 const update=e=>{const field=e.target.dataset.guideField;if(!field)return;const s=options.state();if((s.state||'ready')!=='ready'||s.phase==='read-only')return;const g=guideRecord(s),value=e.target.type==='checkbox'?e.target.checked:e.target.value;if(s.guideView==='launch-guide'){g[field]=value;return}if(field.startsWith('stage-')){const stages=[...(g.stages||[])];stages[Number(field.slice(6))-1]=value;updateCreation(g,'stages',stages)}else updateCreation(g,field,value)};host.addEventListener('input',update);host.addEventListener('change',update);
 host.addEventListener('click',e=>{const b=e.target.closest('[data-guide]');if(!b||b.disabled)return;const s=options.state(),g=guideRecord(s),a=b.dataset.guide;if((s.state||'ready')!=='ready'||s.phase==='read-only')return;g.notice='';
 if(a==='another'){const d=creationRecord(s,true);options.navigate('launch-start',{estate:d.estate,draftId:d.draftId,guideProject:null});return}
 if(a==='mode')updateCreation(g,'mode',b.dataset.mode)
 if(a==='scan'||a==='scan-state'){g.scan=a==='scan'?'ready':b.dataset.state;g.candidates=['ready','partial'].includes(g.scan)?[{name:'Website',path:(g.scanRoot||'/projects')+'/website'},{name:'Notes',path:(g.scanRoot||'/projects')+'/notes'}]:[]}
 if(a==='candidate'){updateCreation(g,'name',b.dataset.name);updateCreation(g,'repo',b.dataset.path);g.step=1}
 if(a==='back')g.step=Math.max(0,g.step-1);
 if(a==='next'){if(g.step===0&&g.mode==='folder'){updateCreation(g,'mode','single');g.step=0}else if(g.step===1&&(!g.name.trim()||!g.purpose.trim()))g.notice='Укажите название и первый полезный результат.';else if(g.step===1)reviewCreation(g,options.fixtures().projects);else g.step=Math.min(2,g.step+1)}
 if(a==='review')reviewCreation(g,options.fixtures().projects)
 if(a==='create'||a==='reconcile'){const r=a==='create'?commitCreation(g,options.create,s):reconcileCreation(g,options.create,s);if(r.ok){const lesson=guideRecord({estate:g.estate,project:r.project.id,guideView:'launch-guide'});lesson.project=r.project.id;options.navigate('launch-guide',{estate:g.estate,project:r.project.id,cohort:'existing',guideProject:null});return}}
 if(a==='unknown')pendCreation(g,options.fixtures().projects)
 if(a==='refused')g.notice='Создание отклонено: выбранный fixture host недоступен. Черновик сохранён, проекта нет.'
 if(a==='save'||a==='cancel'){options.navigate('launch-home',{estate:g.estate,draftId:g.draftId});return}
 if(a==='discard'){if(g.pending){g.notice='Создание подтверждается. Проверьте исход того же запроса.'}else{discardCreation(g);options.navigate('launch-home',{estate:g.estate,draftId:null});return}}
 if(a==='inspect'){const repo=normalizedCreation(g).repo;g.inspection=repo?{repo,revision:'demo-read-1',name:repo.split('/').filter(Boolean).at(-1),purpose:'Проверяемый результат для '+repo,source:'README.md:1–2 · демонстрационный снимок',status:'review',decisions:{}}:null;if(!repo)g.notice='Сначала укажите репозиторий.'}
 if(a==='unavailable')g.inspection={status:'unavailable'}
 if(a==='suggestion'){const i=g.inspection,field=b.dataset.field;if(i?.status==='review'&&['name','purpose'].includes(field)){i.decisions[field]=b.dataset.choice;if(b.dataset.choice==='accept')updateCreation(g,field,i[field])}}
 if(a==='chat'||a==='example'){options.chat(a==='example'?b.dataset.prompt:'Собери изменения с прошлого визита');return}
 if(a==='task'){const result=options.task({id:g.key+':first-task',requestId:g.key+':first-task:'+s.project,project:s.project,title:g.firstTask||options.fixtures().projects.find(p=>p.id===s.project)?.purpose,source:'guided-onboarding:v1'});if(result.ok){g.project=s.project;g.task=result.entityRef.params.task;g.notice='Задача сохранена; запуск не начат.'}else g.notice=result.error}
 if(a==='board'){if(!g.topic){const result=options.topic({id:'guide:'+s.project+':v1',project:s.project,title:'Знакомство с доской',prompt:'Здесь обсуждаем вопросы, требующие внимания. Закройте эту учебную тему после прочтения; рабочая задача остаётся открытой.',source:'guided-onboarding:v1',kind:'topic'});if(result.ok)g.topic=result.entityRef.params.item;else g.notice=result.error}if(g.topic){options.navigate('launch-board',{project:s.project,scope:'project',item:g.topic});return}}
 if(a==='skip'||a==='complete'){g.dismissed=true;if(a==='complete'&&g.task&&g.topic)g.finished=true;options.navigate('launch-project',{project:s.project});return}options.rerender();
 })
}

function creationAdvanced(g,fixtures){
 const selected=(a,b)=>a===b?'selected':''
 const i=g.inspection
 return `<details class="disclosure" ${i?'open':''}><summary>Исполнитель и начальная конфигурация</summary><label class="field">Исполнитель<select data-guide-field="provider">${[['later','Настроить позже'],['claude-code','Claude Code'],['codex','Codex'],['fabric','Fabric']].map(([value,label])=>`<option value="${value}" ${selected(g.provider,value)}>${label}</option>`).join('')}</select></label><label class="field">С чего начинаем<select data-guide-field="starter">${[['idea','Пустой проект и цель'],['software','Разработка продукта'],['repository','Существующий репозиторий'],['observer','Наблюдение за портфелем']].map(([value,label])=>`<option value="${value}" ${selected(g.starter,value)}>${label}</option>`).join('')}</select></label><p>Привязка не активируется до независимой проверки. Все автоматические циклы изначально выключены.</p><label class="field">Наблюдаемые проекты<select data-guide-field="target"><option value="">Не выбраны</option>${fixtures.projects.filter(p=>(p.estate||'team-estate')===g.estate&&!p.archived&&!p.purged).map(p=>`<option value="${ge(p.id)}" ${selected(g.target,p.id)}>${ge(p.name)}</option>`).join('')}</select></label><label class="choice"><input type="checkbox" data-guide-field="futureConsent" ${g.futureConsent?'checked':''}> Разрешить включение будущих проектов в scope наблюдения</label><p>Подтверждается в обзоре перед созданием. По умолчанию будущие проекты не включены.</p><h3>Начальные этапы маршрута</h3>${[0,1,2].map(n=>gf('Этап '+(n+1),'stage-'+(n+1),g.stages?.[n]||'')).join('')}<p>Роли software: Product manager, Builder, Reviewer. Все кандидаты требуют отдельной проверки; автоматические cycles на паузе.</p>${normalizedCreation(g).repo?gb('Исследовать репозиторий','inspect')+gb('Проверить отказ исследования','unavailable'):''}${i?.status==='unavailable'?'<p>Исследование недоступно. Можно ввести цель и название вручную; проекта ещё нет.</p>':i?.status==='review'?`<p>${ge(i.repo+' / '+i.revision+' / '+i.source)}</p><p>Учебные данные, реальный репозиторий не читался. Каждое предложение принимается отдельно.</p>${['name','purpose'].map(field=>`<p>${ge(i[field])} · ${ge(i.decisions[field]||'Ещё не рассмотрено')}${gb('Принять','suggestion',`data-field="${field}" data-choice="accept"`)}${gb('Отклонить','suggestion',`data-field="${field}" data-choice="reject"`)}</p>`).join('')}`:''}</details>`
}
