// The Board is a read-time union. Reading an event never resolves an obligation.
const be=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
export function readObligations(state,fixtures,project=null) {
  const active=id=>fixtures.projects.some(p=>p.id===id&&!p.archived&&!p.purged),ops=state.ops||{},weight=id=>({critical:40,active:25,steady:10,paused:0})[fixtures.projects.find(p=>p.id===id)?.tier||'active'],rows=[]
  for(const q of fixtures.questions.filter(q=>q.state==='open'&&active(q.project))){const components=q.priority_components||{blocking:0,breadth:0,age:0,kind_weight:{approval:15,access:15,decision:10,priority:5,fact:0}[q.kind]||0,goal_proximity:0,project_weight:weight(q.project)};rows.push({...q,record_kind:'question',view:'question',params:{question:q.id},rank:Object.values(components).reduce((a,b)=>a+b,0),components,source:'questions/'+q.id,reason:'Нужен записанный ответ; прочтение не закрывает вопрос.'})}
  const add=(id,kind,record,score,view,params,reason)=>rows.push({id,record_kind:kind,project:record.project,title:record.title||record.name||id,owner:record.owner||record.agent||'Оператор',view,params,rank:score+weight(record.project),components:{derived:score,project_weight:weight(record.project)},source:kind+'/'+record.id,reason})
  for(const t of Object.values(ops.tasks||{})){if(!active(t.project))continue;if(t.state==='review')add('review:'+t.id,'review',t,25,'task',{task:t.id},'Задача на проверке. Исчезнет после изменения состояния задачи.');if(t.lastAdmission?.kind==='admission-refused'&&t.state==='backlog')add('refused:'+t.id,'refused',t,55,'launch',{task:t.id},'Последний допуск отказан. Нужна свежая проверка условий, не отметка прочтения.')}
  for(const p of fixtures.proposals||[])if(p.status==='open'&&active(p.project))add('proposal:'+p.id,'proposal',p,35,'cross-project-proposal',{proposal:p.id,source:p.source},'Цепочка дошла до границы. Решение принимает целевой Product manager.')
  for(const s of Object.values(ops.sessions||{}))if(s.status==='abandoned'&&active(s.project))add('session:'+s.id,'abandoned',s,20,'session',{session:s.id},'Сессия оставлена. Историю и продолжение нужно разобрать.')
  for(const lease of fixtures.leases||[])if(active(lease.project)&&['expired-unreconciled','owner-unknown'].includes(lease.status))add('lease:'+lease.id,'lease',{...lease,title:'Сверить прежнего владельца '+lease.task},45,'harness',{lease:lease.id,task:lease.task},'TTL истёк; это не доказательство остановки процесса. Сначала сверка и fencing, затем release.')
  for(const r of rows){const source=r.record_kind==='question'?fixtures.questions.find(q=>q.id===r.id):r.record_kind==='lease'?fixtures.leases.find(l=>'lease:'+l.id===r.id):null;const at=source?.asked_at||source?.created_at||source?.recorded_at;const minutes=at?Math.max(0,Math.floor((Date.parse(fixtures.as_of)-Date.parse(at))/60000)):null;r.age_minutes=Number.isFinite(minutes)?minutes:null;r.observed_at=fixtures.as_of}
  return rows.filter(r=>!project||r.project===project).sort((a,b)=>b.rank-a.rank||a.id.localeCompare(b.id))
}
export function renderObligationRows(rows,limit=Infinity){
  return rows.slice(0,limit).map(r=>`<article class="item" data-obligation="${be(r.id)}"><div><strong>${be(r.title)}</strong><p class="meta">${be(r.id+' · '+r.project+' · '+r.owner)} · приоритет ${r.rank} · возраст ${r.age_minutes===null?'неизвестен':r.age_minutes+' мин'}</p><p>${be(r.reason)}</p><details class="disclosure"><summary>Почему здесь · ${be(r.source)}</summary><pre class="code-block">${be(JSON.stringify({source:r.source,rank:r.rank,components:r.components,observed_at:r.observed_at,age_minutes:r.age_minutes},null,2))}</pre></details></div><a class="button" href="#view-${r.view}?${be(new URLSearchParams({project:r.project,...r.params}))}">Разобрать</a></article>`).join('')||'<p>В прочитанной области обязательств нет.</p>'
}
