// #region test-stack — docs: README.md#the-disposable-test-stack
// The one place a database-backed probe learns where its database is (2026-10-03 release
// review, iteration 1, findings 2 and 3).
//
// WHY THIS EXISTS. Until this module, about twenty probes ran `supabase status` at the
// repository root and took whatever it answered. That is the operator's LIVE stack — project
// `fabric`, API 54321, DB 54322 — the same database the desktop app keeps their real estates
// in. The probes wrote random-id estates, persons and projects into it and cleaned up only part
// of them (768 estates, 3 540 projects and 996 persons of residue were measured), one revoked
// SELECT on `memory_facts` there for the length of a call, and `ci.sh full` ran
// `supabase migration up` against it. An override could not help: the probes overwrote
// `SUPABASE_URL` with the root's answer.
//
// THE RULE NOW. A probe reads its connection from the environment the tier sets, and only from
// there: `SUPABASE_URL`, `SUPABASE_SERVICE_ROLE_KEY`, `DATABASE_URL`, and `FABRIC_TEST_STACK`
// naming the disposable project. Nothing falls back to `supabase status`. Before anything
// connects, the address is compared with the live stack's ports — read from the root
// `supabase/config.toml`, plus 54321/54322 whatever the file says — and a match is REFUSED.
// The disposable stack itself is made by `scripts/test-stack.mjs`.

import { readFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')

/** The ports the live stack listens on whatever its config says today (README, external-contracts). */
export const LIVE_DEFAULT_PORTS = Object.freeze([54321, 54322])

/** A disposable project id. Anything else is never stopped with `--no-backup` by this tooling. */
export const DISPOSABLE_ID = /^fabric_test_[0-9a-f]{6,32}$/

// Where each port of a disposable stack sits inside its block of ten. Distinct by construction;
// the test pins that, because two services on one port fail as a start that "hangs".
export const PORT_OFFSETS = Object.freeze({
  'db.shadow_port': 0,
  'api.port': 1,
  'db.port': 2,
  'studio.port': 3,
  'local_smtp.port': 4,
  'edge_runtime.inspector_port': 6,
  'analytics.port': 7,
  'db.pooler.port': 9
})
export const PORT_BLOCK = 10

const SECTION = /^\s*\[([^\]]+)\]\s*(?:#.*)?$/
const ASSIGN = /^(\s*)([A-Za-z0-9_]+)(\s*=\s*)(.+?)(\s*(?:#.*)?)$/

/**
 * The project id and every port a Supabase `config.toml` declares, keyed `section.key`.
 * A deliberately small reader: the file is generated by the CLI and the two things read here
 * are plain scalars. Commented lines are ignored, so a commented-out port is not a port.
 */
export function parseStackConfig(text) {
  let section = ''
  let projectId = null
  const ports = {}
  for (const raw of String(text).split('\n')) {
    if (/^\s*#/.test(raw)) continue
    const s = raw.match(SECTION)
    if (s) { section = s[1].trim(); continue }
    const a = raw.match(ASSIGN)
    if (!a) continue
    const [, , key, , value] = a
    if (!section && key === 'project_id') projectId = value.replace(/^"(.*)"$/, '$1')
    if (/(^|_)port$/.test(key) && /^\d+$/.test(value)) ports[`${section}.${key}`] = Number(value)
  }
  return { projectId, ports }
}

/** The live stack: what the repository root declares, and the two ports it has always had. */
export function liveStack(root = REPO_ROOT) {
  const file = path.join(root, 'supabase', 'config.toml')
  const parsed = existsSync(file) ? parseStackConfig(readFileSync(file, 'utf8')) : { projectId: 'fabric', ports: {} }
  const ports = new Set([...LIVE_DEFAULT_PORTS, ...Object.values(parsed.ports)])
  return {
    projectId: parsed.projectId ?? 'fabric',
    apiPort: parsed.ports['api.port'] ?? 54321,
    dbPort: parsed.ports['db.port'] ?? 54322,
    ports
  }
}

/**
 * The root config rewritten for a disposable stack: its own project id, and every port moved into
 * the block that starts at `base`. A port key this table does not know still moves — to the next
 * unused offset — so a service added to the config later cannot keep a live port by accident.
 */
export function disposableConfig(text, { projectId, base }) {
  if (!DISPOSABLE_ID.test(projectId)) throw new Error(`not a disposable project id: ${projectId}`)
  if (!Number.isInteger(base) || base < 1024 || base + PORT_BLOCK > 65535) throw new Error(`bad base port: ${base}`)
  const used = new Set(Object.values(PORT_OFFSETS))
  const extra = new Map()
  const offsetOf = key => {
    if (key in PORT_OFFSETS) return PORT_OFFSETS[key]
    if (!extra.has(key)) {
      let o = 0
      while (used.has(o)) o++
      if (o >= PORT_BLOCK) throw new Error(`more ports than the block holds: ${key}`)
      used.add(o); extra.set(key, o)
    }
    return extra.get(key)
  }
  let section = ''
  let sawId = false
  const out = String(text).split('\n').map(raw => {
    if (/^\s*#/.test(raw)) return raw
    const s = raw.match(SECTION)
    if (s) { section = s[1].trim(); return raw }
    const a = raw.match(ASSIGN)
    if (!a) return raw
    const [, lead, key, eq, value, tail] = a
    if (!section && key === 'project_id') { sawId = true; return `${lead}${key}${eq}"${projectId}"${tail}` }
    if (/(^|_)port$/.test(key) && /^\d+$/.test(value)) return `${lead}${key}${eq}${base + offsetOf(`${section}.${key}`)}${tail}`
    return raw
  })
  if (!sawId) out.unshift(`project_id = "${projectId}"`)
  return out.join('\n')
}

const LOOPBACK = new Set(['127.0.0.1', 'localhost', '[::1]', '::1'])

function portOf(value, defaultPort) {
  try {
    const u = new URL(value)
    return { host: u.hostname, port: u.port ? Number(u.port) : defaultPort }
  } catch {
    return null
  }
}

/**
 * Every reason this environment must NOT be used by a database-backed probe. Empty means it names
 * a disposable stack. Pure, so the refusals are tested one by one (scripts/test/test-stack.test.mjs).
 */
export function checkTestStack(env, live = liveStack()) {
  const reasons = []
  const need = ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY', 'DATABASE_URL', 'FABRIC_TEST_STACK']
  for (const name of need) if (!env[name]) reasons.push(`${name} is not set — the tier sets it for a disposable stack`)
  if (env.FABRIC_TEST_STACK && env.FABRIC_TEST_STACK === live.projectId)
    reasons.push(`FABRIC_TEST_STACK names the live project "${live.projectId}"`)
  if (env.FABRIC_TEST_STACK && !DISPOSABLE_ID.test(env.FABRIC_TEST_STACK))
    reasons.push(`FABRIC_TEST_STACK "${env.FABRIC_TEST_STACK}" is not a disposable project id (fabric_test_<hex>)`)
  const targets = [
    ['SUPABASE_URL', env.SUPABASE_URL, 80],
    ['DATABASE_URL', env.DATABASE_URL, 5432]
  ]
  for (const [name, value, defaultPort] of targets) {
    if (!value) continue
    const at = portOf(value, defaultPort)
    if (!at) { reasons.push(`${name} is not a URL`); continue }
    if (live.ports.has(at.port))
      reasons.push(`${name} points at port ${at.port}, which is the LIVE stack's (API ${live.apiPort}, DB ${live.dbPort}) — the operator's database`)
    if (!LOOPBACK.has(at.host)) reasons.push(`${name} host ${at.host} is not loopback — a disposable stack is local by construction`)
  }
  return reasons
}

/**
 * The environment a database-backed probe runs with, or a refusal and exit 1 BEFORE any client
 * exists. A refusal is a FAIL, not a skip: a probe that asserts nothing must not read as green
 * (M110). Returns a copy of `process.env`, ready to hand to a child.
 */
export function probeEnv({ env = process.env, live = liveStack(), exit = code => process.exit(code), log = console.log } = {}) {
  const reasons = checkTestStack(env, live)
  if (reasons.length) {
    for (const r of reasons) log(`  FAIL ${r}`)
    log('  FAIL refusing to connect: database probes run only against a disposable stack — `bash scripts/ci.sh full`, or `node scripts/test-stack.mjs run -- <command>`')
    exit(1)
    return null
  }
  return { ...env }
}
// #endregion test-stack
