#!/usr/bin/env python3
"""Builds 2026-10-05-fix-list.md from the audit tables in this folder and dispositions.json.

Reads every finding row (`| ID | P0..P3 | …`) of the seven area reports — 2026-10-05-architecture.md already
merges its two helper drafts, 2026-10-05-area2.md and 2026-10-05-area45.md, so those are not read again — and writes one
table per severity with the release-0.3.2 disposition of each finding. Run from anywhere:
    python3 docs/reports/2026-10-05-release-032-audit/raw/build-fix-list.py
"""
import json, pathlib, re
HERE = pathlib.Path(__file__).parent
SOURCES = ['2026-10-05-scn-001-022.md', '2026-10-05-scn-023-045.md', '2026-10-05-scn-046-068.md', '2026-10-05-scn-069-090.md', '2026-10-05-scn-091-112.md', '2026-10-05-scn-113-134.md', '2026-10-05-architecture.md']
disp = json.loads((HERE / 'dispositions.json').read_text())
rows = []
for name in SOURCES:
    head = None
    for line in (HERE / name).read_text().splitlines():
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        if cells and cells[0] == 'ID': head = cells; continue
        if head and len(cells) >= len(head) - 1 and re.fullmatch(r'[A-Z][0-9]*-[0-9]+', cells[0]) and re.fullmatch(r'P[0-3]', cells[1]):
            row = dict(zip(head, cells))
            where = row.get('Scenario/Screen') or row.get('Area', '')
            finding = next(v for k, v in row.items() if k.startswith('Finding'))
            first = re.split(r'(?<=[.!?])\s', finding, maxsplit=1)[0]
            if len(first) > 240: first = first[:237].rstrip() + '…'
            rows.append({'id': cells[0], 'sev': cells[1], 'where': where, 'finding': first, 'source': name})
seen = set()
for r in rows:
    if r['id'] in seen: raise SystemExit(f"duplicate id {r['id']}")
    seen.add(r['id'])
unknown = set(disp) - seen
if unknown: raise SystemExit(f'dispositions name unknown ids: {sorted(unknown)}')
default = disp.get('_default') if '_default' in disp else None
def status(i):
    d = disp.get(i)
    if d: return d
    return {'P0': None, 'P1': None}.get(next(r['sev'] for r in rows if r['id'] == i), {'state': 'deferred', 'ref': 'CO-215' if next(r['sev'] for r in rows if r['id'] == i) == 'P2' else 'CO-216'})
out = ['# Release 0.3.2 audit: the fix list', '',
       'Generated by `raw/build-fix-list.py` from the seven area reports and `raw/dispositions.json`. Do not edit by hand.', '']
counts = {}
for sev in ['P0', 'P1', 'P2', 'P3']:
    group = [r for r in rows if r['sev'] == sev]
    out += [f'## {sev} ({len(group)})', '', '| ID | Where | Finding | 0.3.2 | Source |', '|---|---|---|---|---|']
    for r in group:
        s = status(r['id'])
        if s is None: raise SystemExit(f"{r['id']} ({sev}) has no disposition: every P0 and P1 must say what happened to it")
        counts[s['state']] = counts.get(s['state'], 0) + 1
        cell = s['state'] + (f" — {s['ref']}" if s.get('ref') else '')
        f = r['finding'].replace('|', '\\|')
        out.append(f"| {r['id']} | {r['where']} | {f} | {cell} | [{r['source']}]({r['source']}) |")
    out.append('')
out.insert(4, 'Totals: ' + ', '.join(f'{k} {v}' for k, v in sorted(counts.items())) + f' — {len(rows)} findings.')
out.insert(5, '')
(HERE / '2026-10-05-fix-list.md').write_text('\n'.join(out) + '\n')
print(f'{len(rows)} findings;', counts)
