import test from 'node:test'
import assert from 'node:assert/strict'
import {createFirstRelease,firstReleaseAction as act} from '../product/first-release.mjs'
import {chatWorkspaceState as ctx,chatWorkspaceSnapshot as snap,renderChatContext,renderChatWidget} from '../product/chat-workspace.mjs'
function setup(){const s=createFirstRelease();s.readiness='ready';for(const path of ['/A','/B']){act(s,'picked',path);act(s,'scan');act(s,'scan-result')}s.chatScope='';s.activeTicket=null;return s}
function send(s,text,key=s.activeTicket?'ticket:'+s.activeTicket:s.chatScope){s.drafts[key]=text;act(s,'send')}
test('chips toggle knowledge without changing conversation, draft, ownership or messages',()=>{const s=setup();s.drafts['']='keep';const [a,b]=s.projects;act(s,'cw-context',a.id);act(s,'cw-context',b.id);assert.deepEqual(ctx(s).projects,[a.id,b.id]);assert.equal(s.chatScope,'');assert.equal(s.drafts[''],'keep');act(s,'cw-context',a.id);assert.deepEqual(ctx(s).projects,[b.id]);act(s,'cw-context','none');assert.deepEqual(ctx(s).projects,[]);act(s,'cw-context','invented');assert.deepEqual(ctx(s).projects,[]);act(s,'cw-context','all');assert.equal(ctx(s).projects.length,2)})
test('messages capture plan and related sources, snapshots cannot be rewritten by later chips',()=>{const s=setup(),a=s.projects[0];a.sources.push({name:'Related',path:'/Ref',role:'related'});s.selected=a.id;act(s,'task','A plan');act(s,'cw-context',a.id);send(s,'Что изменилось?');const saved=s.messages[''][0].context;assert.equal(saved.projects[0].plan[0].title,'A plan');assert.equal(saved.projects[0].sources.length,2);act(s,'cw-context','none');a.tasks[0].title='Changed';assert.equal(saved.projects[0].plan[0].title,'A plan');assert.equal(saved.projects.length,1)})
test('multi-project command requires an eligible destination and applies once to that owner',()=>{const s=setup();act(s,'cw-context','all');send(s,'Создай задачу проверить вход');const m=s.messages[''][1];assert.equal(m.command,'task');assert.equal(s.projects.reduce((n,p)=>n+p.tasks.length,0),0);act(s,'widget-command',{index:1,project:'outside'});assert.equal(s.board.length,0);const b=s.projects[1];act(s,'widget-command',{index:1,project:b.id});assert.equal(s.board.length,1);assert.equal(s.board[0].project,b.id);const board=s.board[0];assert.equal(board.outcome.discussionContext.projects.length,2);act(s,'outcome-apply',board.id);assert.equal(b.tasks.length,1);assert.equal(b.tasks[0].context.discussionContext.projects.length,2);assert.equal(s.projects[0].tasks.length,0)})
test('stale command and invalid command cannot act; none does not erase history',()=>{const s=setup(),a=s.projects[0];act(s,'cw-context',a.id);send(s,'Создай задачу');a.contextRevision++;act(s,'widget-command',{index:1,project:a.id});assert.match(s.notice,/Контекст изменился/);assert.equal(s.board.length,0);act(s,'cw-context','none');assert.equal(s.messages[''].length,2)})
test('ticket owner remains, extra references and separate new conversation work',()=>{const s=setup(),[a,b]=s.projects;s.selected=a.id;act(s,'topic','Question');act(s,'cw-context',b.id);act(s,'cw-context','none');assert.deepEqual(ctx(s).projects,[a.id]);assert.match(ctx(s).error,/остаётся/);const id=s.activeTicket;send(s,'Нужен план');act(s,'new-chat');assert.equal(s.activeTicket,null);assert.equal(ctx(s).projects.length,0);assert.equal(s.messages['ticket:'+id].length,3);act(s,'close-chat');act(s,'reopen-chat');assert.equal(s.chat,true)})
test('attachments are bounded fixtures and validated URLs; metadata logs only after send',()=>{const s=setup();act(s,'cw-file','/private.txt');assert.equal(ctx(s).attachments.length,0);act(s,'cw-file','brief.md');act(s,'cw-file','brief.md');assert.equal(ctx(s).attachments.length,1);for(const bad of ['javascript:alert(1)','https://user:password@example.com','https://example.com?token=secret']){ctx(s).link=bad;act(s,'cw-link');assert.match(ctx(s).error,/HTTP/)}ctx(s).link='https://example.com/brief';act(s,'cw-link');assert.equal(ctx(s).attachments.length,2);act(s,'send');assert.equal(s.messages[''][0].context.attachments.length,2);assert.equal(ctx(s).attachments.length,0);assert.equal(s.messages[''][0].text,'Разбери приложенные материалы')})
test('short selections render buttons, long lists limit composer and widget payload is escaped',()=>{const s=setup();assert.doesNotMatch(renderChatContext(s),/<select|<details/);const html=renderChatWidget(s,{command:'task',context:{projects:[{id:'p',name:'<script>'}]}},1);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>/)})
test('stop widget is tied to the observed run and cannot stop a replacement',()=>{const s=setup(),p=s.projects[0];s.selected=p.id;act(s,'task','Run');act(s,'run');act(s,'cw-context',p.id);send(s,'Останови агента');const old=s.run.id;act(s,'stop');act(s,'stop-result');act(s,'resume','claude-code');assert.notEqual(s.run.id,old);act(s,'widget-command',{index:1,project:p.id});assert.equal(s.run.status,'running');assert.match(s.notice,/запуск уже изменился/)})
test('criteria refinement retains attachment evidence in accepted task and run',()=>{const s=setup(),p=s.projects[0];s.selected=p.id;act(s,'topic','Review brief');const b=s.board[0];act(s,'cw-file','brief.md');send(s,'Проверить первый вход');send(s,'Критерий: входит с клавиатуры');act(s,'outcome-apply',b.id);assert.equal(p.tasks[0].context.discussionContext.attachments[0].name,'brief.md');act(s,'outcome-run',b.id);assert.equal(s.run.context.discussionContext.attachments.length,1)})
test('new conversation retains the previous draft and history can reopen it',()=>{const s=setup();send(s,'Review');s.drafts['']='unsent';act(s,'new-chat');send(s,'Another');act(s,'cw-open','');assert.equal(s.chatScope,'');assert.equal(s.drafts[''],'unsent');assert.equal(s.messages[''][0].text,'Review')})
test('draft-only conversations and attached-only drafts remain reachable',()=>{const s=setup();act(s,'new-chat');const key=s.chatScope;s.drafts[key]='unsent only';act(s,'cw-file','brief.md');act(s,'new-chat');act(s,'cw-open',key);assert.equal(s.chatScope,key);assert.equal(s.drafts[key],'unsent only');assert.equal(ctx(s).attachments[0].name,'brief.md')})
test('encoded query credentials and fragment credentials are rejected before attachment storage',()=>{const s=setup();for(const url of ['https://example.com/#token=secret','https://example.com/?%74oken=secret','https://example.com/#access_token=abc']){ctx(s).link=url;act(s,'cw-link');assert.equal(ctx(s).attachments.length,0);assert.match(ctx(s).error,/HTTP/)}})
test('generic create shortcut asks for intent instead of proposing a task named Create task',()=>{const s=setup();act(s,'cw-context',s.projects[0].id);send(s,'Создай задачу');act(s,'widget-command',{index:1,project:s.projects[0].id});assert.equal(s.board[0].title,'Новая задача');assert.equal(s.board[0].outcome,undefined);assert.equal(s.projects[0].tasks.length,0)})
