// Isolated headless fixture QA: own loopback server and temporary browser profile.
// Never invokes Fabric/native IPC/providers/filesystem discovery/DB.
// FABRIC_PLAYWRIGHT_MODULE selects Playwright; FABRIC_CHROME may select an executable.
// Screenshots stay machine-only in FABRIC_BROWSER_OUTPUT or an ephemeral temp directory.
// #region co180-scan-browser — docs: docs/ux/scenarios.md#scn-128-scan-a-projects-folder-and-tick-what-becomes-a-project
// Visibility is awaited (waitFor), never sampled (isVisible): a loaded host renders after the click
// returns, and a sampled check failed once in the fast gate on 2026-10-04. The committed receipt is rewritten only
// with FABRIC_CO180_RECORD_RECEIPT=1; a gate run writes beside its screenshots, so it never dirties the tree.
const {chromium}=require(process.env.FABRIC_PLAYWRIGHT_MODULE || 'playwright');const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),crypto=require('crypto');
const repo=path.resolve(__dirname,'../..'),root=repo+'/docs',out=process.env.FABRIC_BROWSER_OUTPUT || fs.mkdtempSync(path.join(require('os').tmpdir(),'fabric-co180-browser-')),report={as_of:new Date().toISOString(),scope:'CO-180 SCN-128 generated target prototype only',tier:'target-only',native_acceptance:'NOT_RUN',headless:true,profile:'isolated temporary browser profile',server:'owned ephemeral loopback',fixtures:'page-local model only; provider/native/filesystem/DB invocation prohibited',checks:[],page_errors:[],external_network_attempts:0,screenshots:[],sources:{}};let server,browser,page,screen,origin,n=0;
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(repo+'/'+f)).digest('hex');for(const f of ['docs/reports/product.html','scripts/product/first-release.mjs','scripts/product/first-release.css','docs/ux/scenarios.md'])report.sources[f]=hash(f);
const snap=()=>page.evaluate(()=>{const s=firstReleaseStore(state);return {scan:s.scan,token:s.scanToken,step:s.scanStep,readiness:s.readiness,projects:s.projects.map(p=>({id:p.id,source:p.source,sources:p.sources})),selected:s.selected,chosen:s.chosenSources,pending:s.pendingImports,results:s.importResults,candidates:s.candidates,startup:s.startupExample}});
const click=a=>screen.locator('[data-r0="'+a+'"]').click();
async function nav(view){await page.evaluate(v=>location.hash='#view-'+v+'?estate='+state.estate,view);await page.evaluate(()=>new Promise(requestAnimationFrame));}
async function fresh(view='r0-source'){await page.goto(origin+'/reports/product.html#view-'+view+'?estate=co180-browser-'+(++n));await page.waitForFunction(()=>document.documentElement.classList.contains('js'));await page.evaluate(()=>{const s=firstReleaseStore(state);s.configured=true;s.readiness='ready';renderRoute(false)})}
async function collection(folder='/Projects'){await screen.locator('[data-r0=source-mode][data-value=collection]').click();await screen.locator('[data-folder-picker=r0-folder]').click();await page.locator('[data-folder-option="'+folder+'"]').click();await page.locator('[data-folder-confirm]').click();await page.waitForFunction(()=>['candidates','candidates-partial'].includes(firstReleaseStore(state).scan));}
async function tick(p){await screen.locator('[data-r0=candidate-toggle][data-value="'+p+'"]').check()}
async function waitScan(s){await page.waitForFunction(s=>firstReleaseStore(state).scan===s,s)}
async function check(id,fn){try{await fn();report.checks.push({id,status:'PASS'})}catch(e){report.checks.push({id,status:'FAIL',reason:e.message.slice(0,900)});console.log('FAIL',id,e.message.slice(0,500))}}
;(async()=>{server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end()}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404);return res.end()}res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'text/javascript');res.end(b)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,...(process.env.FABRIC_CHROME ? {executablePath:process.env.FABRIC_CHROME} : {})});report.browser=await browser.version();page=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});screen=page.locator('#product-screen');page.setDefaultTimeout(7000);page.on('pageerror',e=>report.page_errors.push(e.message));await page.route('**/*',r=>{if(r.request().url().startsWith(origin+'/'))return r.continue();report.external_network_attempts++;return r.abort()});
await check('actual_onboarding_fixture_probe_and_parent_discovery',async()=>{await fresh('r0-setup');await page.evaluate(()=>{firstReleaseStore(state).readiness='unchecked';renderRoute(false)});await click('identity');await click('probe');await page.waitForFunction(()=>firstReleaseStore(state).readiness==='ready');await screen.getByRole('link',{name:'Выбрать проект',exact:true}).click();await collection();assert.equal((await snap()).candidates.length,3)});
await check('two_ticks_two_projects_unticked_absent_visible_summary',async()=>{await tick('/Projects/atlas');await tick('/Projects/orbit');await click('candidate-import');await waitScan('imported');const s=await snap();assert.equal(s.projects.length,2);assert.deepEqual(s.projects.map(p=>p.source),['/Projects/atlas','/Projects/orbit']);assert.equal(new Set(s.projects.map(p=>p.id)).size,2);assert(s.projects.every(p=>p.sources.length===1));assert.equal(s.results.length,2);await screen.getByRole('link',{name:'Открыть первый проект'}).waitFor({state:'visible',timeout:10000});assert.equal(await screen.getByRole('link',{name:'Открыть проект',exact:true}).count(),2);for(const width of [1280,390]){await page.setViewportSize({width,height:900});await page.screenshot({path:out+'/summary-'+width+'.png',fullPage:true});report.screenshots.push({name:'summary-'+width+'.png',width,state:'imported',location:'machine-only browser output'})}});
await check('kept_candidates_existing_disabled_exact_project_link',async()=>{const before=await snap();await click('candidates-return');for(const p of before.projects){const row=screen.locator('input[data-value="'+p.source+'"]').locator('xpath=ancestor::div[contains(@class,"r0-source-row")]');assert(await row.locator('input').isDisabled());assert.equal(new URL(await row.getByRole('link').getAttribute('href'),'http://fixture').hash.split('project=')[1],p.id)}assert.equal((await snap()).candidates.length,3);await tick('/Projects/empty');await click('candidate-import');await waitScan('imported');assert.equal((await snap()).projects.length,3)});
await check('failed_batch_explicit_retry_retains_exact_batch_no_duplicates',async()=>{await fresh();await collection();await tick('/Projects/atlas');await tick('/Projects/orbit');await page.evaluate(()=>firstReleaseStore(state).scanOutcome='failed');await click('candidate-import');await waitScan('failed');const failed=await snap();assert.equal(failed.projects.length,0);assert.deepEqual(failed.pending,['/Projects/atlas','/Projects/orbit']);await page.evaluate(()=>firstReleaseStore(state).scanOutcome='done');await screen.getByRole('button',{name:'Повторить чтение'}).click();await waitScan('imported');assert.equal((await snap()).projects.length,2)});
await check('cancelled_batch_fences_late_timer_and_explicit_retry',async()=>{await fresh();await collection();await tick('/Projects/atlas');await tick('/Projects/orbit');await click('candidate-import');await click('scan-cancel');await waitScan('cancelled');const stopped=await snap();assert.equal(stopped.projects.length,0);assert.deepEqual(stopped.pending,['/Projects/atlas','/Projects/orbit']);await page.waitForTimeout(2300);assert.equal((await snap()).projects.length,0);await screen.getByRole('button',{name:'Повторить чтение'}).click();await waitScan('imported');assert.equal((await snap()).projects.length,2)});
await check('mixed_row_failure_retry_only_remaining_preserves_first_id',async()=>{await fresh();await collection('/Data');await tick('/Data/Website');await tick('/Data/Notes');await page.evaluate(()=>firstReleaseStore(state).importOutcomes={'/Data/Notes':'failed'});await click('candidate-import');await waitScan('import-partial');const partial=await snap();assert.equal(partial.projects.length,1);assert.equal(partial.projects[0].source,'/Data/Website');assert.deepEqual(partial.pending,['/Data/Notes']);assert.equal(partial.results[1].status,'failed');await screen.getByText('Не удалось добавить. Выбор сохранён.').waitFor({state:'visible',timeout:10000});await page.evaluate(()=>delete firstReleaseStore(state).importOutcomes);await screen.getByRole('button',{name:'Повторить для оставшихся'}).click();await waitScan('imported');const retried=await snap();assert.equal(retried.projects.length,2);assert.equal(retried.projects[0].id,partial.projects[0].id);assert.deepEqual(retried.projects[0],partial.projects[0]);assert.equal(new Set(retried.projects.map(p=>p.source)).size,2)});
await check('nested_worktree_manual_warning_select_all_excludes_parts',async()=>{await fresh();await collection();await page.evaluate(()=>{const s=firstReleaseStore(state);s.candidates.push({name:'atlas-worktree',path:'/Projects/atlas-worktree',kind:'worktree'},{name:'atlas-nested',path:'/Projects/atlas/nested',kind:'nested'});renderRoute(false)});await click('candidate-all');assert.deepEqual((await snap()).chosen,['/Projects/atlas','/Projects/orbit','/Projects/empty']);assert.equal(await screen.getByText('Часть другого проекта. Выбирайте вручную, если нужен отдельный проект.').count(),2);await tick('/Projects/atlas-worktree');await tick('/Projects/atlas/nested');assert.equal((await snap()).chosen.length,5);for(const width of [390,1280]){await page.setViewportSize({width,height:900});const dim=await screen.evaluate(el=>({scroll:el.scrollWidth,client:el.clientWidth}));assert(dim.scroll<=dim.client+1,'discovery horizontal overflow '+JSON.stringify(dim));const visual=await screen.evaluate(el=>{const box=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}};const dock=box(el.querySelector('.r0-fabric-dock'));const targets=[...el.querySelectorAll('.r0-source-choice small')].filter(e=>e.textContent.includes('Часть другого проекта')).concat([...el.querySelectorAll('[data-r0=candidate-import]')]).map(e=>({label:e.textContent,rect:box(e)}));return {dock,targets,intersections:targets.filter(t=>dock.x<t.rect.right&&dock.right>t.rect.x&&dock.y<t.rect.bottom&&dock.bottom>t.rect.y).length,dock_position:getComputedStyle(el.querySelector('.r0-fabric-dock')).position}});report.visual_geometry??=[];report.visual_geometry.push({width,...visual});assert.equal(visual.intersections,0,'dock intersects warning or import CTA');assert.equal(visual.dock_position,'static');await page.screenshot({path:out+'/discovery-'+width+'.png',fullPage:true});report.screenshots.push({name:'discovery-'+width+'.png',width,state:'candidates-with-manual-parts',location:'machine-only browser output'})}});
await check('partial_parent_and_row_summary_preserved',async()=>{await fresh();await page.evaluate(()=>firstReleaseStore(state).scanOutcome='partial');await collection('/Data');assert.equal((await snap()).scan,'candidates-partial');await tick('/Data/Website');await click('candidate-import');await waitScan('imported');await screen.getByText('Список найденных проектов неполный: часть папок недоступна.').waitFor({state:'visible',timeout:10000});await screen.getByText('Обзор неполный: часть источников недоступна.').waitFor({state:'visible',timeout:10000});await click('candidates-return');assert.equal((await snap()).scan,'candidates-partial');assert(await screen.locator('[data-value="/Data/Website"] input').count()===0);assert(await screen.locator('input[data-value="/Data/Website"]').isDisabled());assert.equal((await snap()).candidates.length,2)});
await check('provider_denied_import_does_not_start',async()=>{await fresh();await collection();await tick('/Projects/atlas');await page.evaluate(()=>firstReleaseStore(state).readiness='auth');const before=await snap();await click('candidate-import');const after=await snap();assert.equal(after.token,before.token);assert.equal(after.scan,'candidates');assert.equal(after.projects.length,0);assert.equal(after.pending,null);await screen.getByText('Нужно войти в аккаунт агента.').waitFor({state:'visible',timeout:10000})});
await check('startup_refusal_and_generic_denied_have_no_domain_effect',async()=>{await fresh();await collection();await tick('/Projects/atlas');const before=await snap();await page.evaluate(()=>{firstReleaseStore(state).startupExample='behind'});await click('candidate-import');const after=await snap();assert.equal(after.token,before.token);assert.equal(after.scan,'candidates');assert.equal(after.projects.length,0);await page.evaluate(()=>{const s=firstReleaseStore(state);s.startupExample='ready';state.state='denied'});await click('candidate-import');assert.equal((await snap()).token,before.token);assert.equal((await snap()).projects.length,0)});
report.status=report.checks.every(x=>x.status==='PASS')&&!report.page_errors.length&&report.external_network_attempts===0?'PASS':'FAIL';for(const f in report.sources)assert.equal(hash(f),report.sources[f],'source changed during QA: '+f);if(report.status!=='PASS')process.exitCode=1;console.log(JSON.stringify({status:report.status,checks:report.checks,page_errors:report.page_errors,external:report.external_network_attempts}));
})().catch(e=>{report.status='BLOCKED';report.blocker=e.message;process.exitCode=1;console.error(e)}).finally(async()=>{await browser?.close();await new Promise(r=>server?.close(r));fs.writeFileSync(process.env.FABRIC_CO180_RECORD_RECEIPT==='1'?repo+'/docs/reports/2026-10-04-cleanup-start/raw/co180-browser.json':path.join(out,'co180-browser.json'),JSON.stringify(report,null,2)+'\n')});

// #endregion co180-scan-browser
