import test from 'node:test'
import assert from 'node:assert/strict'
import {createFirstRelease,firstReleaseAction,firstReleaseStores,renderFirstRelease} from '../product/first-release.mjs'
import {memoryWorkspaceState,memoryWorkspaceRows,memoryWorkspaceResults,memoryWorkspaceAction,memoryWorkspaceAttachment,renderMemoryWorkspace} from '../product/memory-workspace.mjs'
import {chatWorkspaceState,chatWorkspaceSnapshot} from '../product/chat-workspace.mjs'
const fixture=()=>{const s=createFirstRelease('memory-test');firstReleaseAction(s,'team-example');return s}
test('empty memory is not a fictional transcript collection',()=>{const s=createFirstRelease();assert.equal(memoryWorkspaceRows(s).length,0);assert.match(renderMemoryWorkspace(s),/Сначала добавьте проект/);assert.equal(memoryWorkspaceAttachment(s,'run:no'),null)})
test('scope supports one, many and none; current session belongs to exact Project',()=>{const s=fixture(),u=memoryWorkspaceState(s);assert.equal(memoryWorkspaceResults(s).length,1);memoryWorkspaceAction(s,'memory-project','all');assert.equal(memoryWorkspaceResults(s).length,2);for(const id of [...u.projects])memoryWorkspaceAction(s,'memory-project',id);assert.equal(memoryWorkspaceResults(s).length,0);assert.match(renderMemoryWorkspace(s),/Выберите проект/)})
test('search matches Russian task and provider; no match stays explicit',()=>{const s=fixture();memoryWorkspaceAction(s,'memory-project','all');memoryWorkspaceState(s).query='оплату';assert.equal(memoryWorkspaceResults(s)[0].author,'Codex');memoryWorkspaceState(s).query='Claude';assert.equal(memoryWorkspaceResults(s)[0].author,'Claude Code');memoryWorkspaceState(s).query='missing';assert.equal(memoryWorkspaceResults(s).length,0);assert.match(renderMemoryWorkspace(s),/Совпадений нет/)})
test('source selection cannot reach outside current selected scope',()=>{const s=fixture(),other=memoryWorkspaceRows(s).find(r=>r.project!==s.selected);memoryWorkspaceAction(s,'memory-select',other.id);assert.equal(memoryWorkspaceState(s).selected,null);assert.equal(memoryWorkspaceAttachment(s,other.id),null)})
test('search and source inspection never launch or stop runs',()=>{const s=fixture(),before=JSON.stringify(s.runsById);memoryWorkspaceAction(s,'memory-project','all');const r=memoryWorkspaceResults(s)[0];memoryWorkspaceAction(s,'memory-select',r.id);memoryWorkspaceAction(s,'memory-tab','pack');renderMemoryWorkspace(s);assert.equal(JSON.stringify(s.runsById),before)})
test('context attachment is immutable and idempotent; existing draft is preserved',()=>{const s=fixture();s.chatScope=s.selected;s.drafts[s.selected]='Keep this';const r=memoryWorkspaceResults(s)[0],before=structuredClone(s.runsById);firstReleaseAction(s,'memory-chat',r.id);firstReleaseAction(s,'memory-chat',r.id);const c=chatWorkspaceState(s);assert.equal(c.attachments.length,1);assert.equal(c.attachments[0].source.run,r.run);assert.equal(s.drafts[s.selected],'Keep this');const snap=chatWorkspaceSnapshot(s);c.attachments[0].text='changed';assert.notEqual(snap.attachments[0].text,'changed');assert.deepEqual(s.runsById,before)})
test('missing and stale-scoped attachment refuses without changing conversation',()=>{const s=fixture(),r=memoryWorkspaceResults(s)[0];memoryWorkspaceAction(s,'memory-project',s.selected);firstReleaseAction(s,'memory-chat',r.id);assert.equal(s.chat,false);assert.match(s.notice,/недоступен/)})
test('past context reflects captured task, not later mutable plan wording',()=>{const s=fixture(),r=memoryWorkspaceResults(s)[0];s.projects.find(p=>p.id===r.project).tasks[0].title='Later title';assert.equal(memoryWorkspaceRows(s).find(x=>x.id===r.id).title,r.title)})
test('HTML is escaped and attachment is redacted before conversation persistence',()=>{const s=fixture(),r=s.runsById[Object.keys(s.runsById)[0]];r.context.task.title='<img src=x>';r.context.task.criteria='password=really-secret-password';memoryWorkspaceAction(s,'memory-project','all');const row=memoryWorkspaceRows(s).find(x=>x.run===r.id);const item=memoryWorkspaceAttachment(s,row.id);assert.ok(!item.text.includes('really-secret-password'));assert.ok(!renderMemoryWorkspace(s).includes('<img src=x>'))})

test('reopening a source preserves explicit conversation scope and draft',()=>{const s=fixture(),r=memoryWorkspaceResults(s)[0];firstReleaseAction(s,'memory-chat',r.id);chatWorkspaceState(s).projects=[];s.drafts[s.chatScope]='Keep scoped draft';firstReleaseAction(s,'close-chat');firstReleaseAction(s,'memory-chat',r.id);assert.deepEqual(chatWorkspaceState(s).projects,[]);assert.equal(s.drafts[s.chatScope],'Keep scoped draft')})
test('existing empty project offers its plan rather than another project',()=>{const s=fixture();s.runsById={};s.board=[];assert.match(renderMemoryWorkspace(s),/>Открыть план</);assert.ok(!renderMemoryWorkspace(s).includes('>Добавить проект</'))})
test('attempt identity and source authorship remain explicit',()=>{const s=fixture(),r=memoryWorkspaceResults(s)[0];memoryWorkspaceAction(s,'memory-select',r.id);const html=renderMemoryWorkspace(s);assert.match(html,/Снимок собран Fabric/);assert.match(html,/Исполнитель/);assert.ok(html.includes(r.run));assert.ok(!html.includes('<dt>Автор</dt>'))})

test('accepted and reworked results leave review in memory status',()=>{const s=fixture(),b=s.board.find(b=>b.task);firstReleaseAction(s,'accept',b.id);memoryWorkspaceAction(s,'memory-open','all');const r=memoryWorkspaceRows(s).find(r=>r.task===b.task);memoryWorkspaceAction(s,'memory-select',r.id);assert.match(renderMemoryWorkspace(s),/результат принят/);const p=s.projects.find(p=>p.id===r.project);p.tasks.find(t=>t.id===r.task).state='review';p.tasks.push({id:'rework',revisesTask:r.task,title:'Fix'});assert.equal(memoryWorkspaceRows(s).find(x=>x.id===r.id).status,'changes')})

test('an unknown explicit Project cannot display previously selected memory',()=>{const s=fixture();firstReleaseStores.set(s.estate,s);memoryWorkspaceAction(s,'memory-open','all');const html=renderFirstRelease('r0-memory',{estate:s.estate,project:'r0-project-missing'});assert.match(html,/Повторить чтение/);assert.ok(!html.includes('Проверить оплату подписки'));assert.equal(s.selected,s.projects[0].id)})

test('recovery example names unknown ending and attaches evidence without changing runtime state',()=>{const s=fixture(),before=JSON.stringify(s.runsById);memoryWorkspaceAction(s,'memory-capture-example');const row=memoryWorkspaceResults(s).find(r=>r.recovered);assert.ok(row);memoryWorkspaceAction(s,'memory-select',row.id);const html=renderMemoryWorkspace(s);assert.match(html,/Завершение не подтверждено/);assert.match(html,/Код выхода/);assert.ok(!html.includes('data-value="undefined"'));const attached=memoryWorkspaceAttachment(s,row.id);assert.equal(attached.source.session,'example-recovered');assert.match(attached.text,/демонстрационные данные/);assert.equal(JSON.stringify(s.runsById),before);memoryWorkspaceAction(s,'memory-capture-example');assert.ok(!memoryWorkspaceRows(s).some(r=>r.recovered))})

test('first project initializes memory scope after an earlier empty visit without overriding later explicit none',()=>{const s=createFirstRelease('early-memory');memoryWorkspaceState(s);firstReleaseAction(s,'team-example');assert.deepEqual(memoryWorkspaceState(s).projects,[s.selected]);memoryWorkspaceAction(s,'memory-project',s.selected);assert.deepEqual(memoryWorkspaceState(s).projects,[])})
