import test from 'node:test'
import assert from 'node:assert/strict'
import {createFirstRelease,firstReleaseAction as act} from '../product/first-release.mjs'
import {teamWorkRows,renderTeamWorkspace} from '../product/team-workspace.mjs'
import {chatWorkspaceSnapshot} from '../product/chat-workspace.mjs'
function setup(){const s=createFirstRelease();act(s,'identity');act(s,'probe');act(s,'probe-result');s.source='/Projects/atlas';act(s,'scan');act(s,'scan-result');return s}
function proposal(){const s=setup();act(s,'plan-chat');const b=s.board[0];s.drafts['ticket:'+b.id]='Проверить вход с клавиатуры';act(s,'send');return {s,b,p:s.projects[0]}}
function send(s,b,text){s.drafts['ticket:'+b.id]=text;return act(s,'send')}
test('text, reviewed dictation and button accept the same proposal exactly once',()=>{for(const mode of ['text','dictation','button']){const {s,b,p}=proposal();const id=b.outcome.id;if(mode==='button')act(s,'outcome-apply',{ticket:b.id,proposal:id,source:'button'});else{if(mode==='dictation')s.voice='review';send(s,b,'Да')}assert.equal(p.tasks.length,1);assert(b.outcome.applied);assert.equal(s.commandReceipts.length,1);assert.equal(s.commandReceipts[0].input,mode);send(s,b,'Да');act(s,'outcome-apply',{ticket:b.id,proposal:id,source:'button'});assert.equal(p.tasks.length,1);assert.equal(s.commandReceipts.length,1)}})
test('questions preserve proposals, refinement supersedes buttons, cancellation has no task effect',()=>{const {s,b,p}=proposal(),old=b.outcome.id;send(s,b,'Почему?');assert.equal(b.outcome.id,old);send(s,b,'Критерий: вход доступен без мыши');assert.notEqual(b.outcome.id,old);assert.equal(b.proposalHistory[0].id,old);act(s,'outcome-apply',{ticket:b.id,proposal:old,source:'button'});assert.equal(p.tasks.length,0);assert.match(s.notice,/изменилось/);send(s,b,'Не надо');assert(b.outcome.declined);send(s,b,'Да');assert.equal(p.tasks.length,0);send(s,b,'Другой следующий шаг');assert(!b.outcome.declined);assert.equal(p.tasks.length,0)})
test('bare agreement has no authority without proposal; a negative sentence cannot accept',()=>{const s=setup();act(s,'plan-chat');const b=s.board[0];send(s,b,'Да');assert.equal(b.outcome,undefined);send(s,b,'Подготовь проверку');send(s,b,'Не принимай, сначала уточним критерий');assert.equal(s.projects[0].tasks.length,0);assert(!b.outcome.applied)})
test('multi-project text destination chooses same command as chip and never defaults on yes',()=>{const s=setup(),a=s.projects[0];s.source='/Projects/orbit';act(s,'scan');act(s,'scan-result');const b=s.projects[1];s.chatScope='';act(s,'cw-context','all');s.drafts['']='Создай задачу';act(s,'send');s.drafts['']='Да';act(s,'send');assert.equal(s.board.length,0);s.drafts['']='для orbit';act(s,'send');assert.equal(s.board.length,1);assert.equal(s.board[0].project,b.id);assert.equal(a.tasks.length,0)})
test('roster shows two projects, direct runs, scoped membership and clears accepted attention',()=>{const s=createFirstRelease();act(s,'team-example');const all=teamWorkRows(s);assert.equal(all.length,2);assert.equal(all[0].state,'review');for(const row of all){assert.equal(act(s,'open-run',row.run),'r0-work');assert.equal(s.selected,row.project);assert.equal(s.run.id,row.run);assert.equal(teamWorkRows(s,row.project).length,1)}const b=s.board.find(b=>b.task);act(s,'accept',b.id);assert.equal(teamWorkRows(s).filter(r=>r.state==='review').length,0);assert.match(renderTeamWorkspace(s),/1 в работе · 0 ждут вас/);const previous=s.run;act(s,'open-run','missing');assert.equal(s.run,previous);assert.match(s.notice,/недоступна/)})
test('continuation preserves agent identity, hides predecessor and keeps other stopped task',()=>{const s=setup(),p=s.projects[0];act(s,'task','A');act(s,'run');const old=s.run;act(s,'stop');act(s,'stop-result');act(s,'resume','native');assert.equal(s.run.agent,old.agent);assert.equal(teamWorkRows(s).length,1);assert.equal(teamWorkRows(s)[0].run,s.run.id);act(s,'stop');act(s,'stop-result');act(s,'task','B');act(s,'run',p.tasks[1].id);const live=s.run;act(s,'open-run',old.id);s.chatScope=p.id;assert.equal(teamWorkRows(s).length,2);assert.equal(chatWorkspaceSnapshot(s).projects[0].run.id,live.id);s.drafts[p.id]='Останови агента';act(s,'send');s.drafts[p.id]='Да';act(s,'send');assert.equal(live.status,'stopping');assert.equal(old.status,'stopped')})
test('rendered card labels are equivalent to their buttons, rework clears attention',()=>{const {s,b,p}=proposal();send(s,b,'Не сейчас');assert(b.outcome.declined);send(s,b,'Подготовить новый вариант');send(s,b,'Добавить задачу');assert.equal(p.tasks.length,1);act(s,'run',p.tasks[0].id);act(s,'deliver');act(s,'open-ticket',s.board.find(b=>b.task===p.tasks[0].id).id);const review=s.board.find(b=>b.id===s.activeTicket);send(s,review,'Доработать контраст кнопок');send(s,review,'Добавить доработку');assert.equal(p.tasks.length,2);assert.equal(teamWorkRows(s)[0].state,'changes');assert.match(renderTeamWorkspace(s),/0 ждут вас/)})
test('typed stop card label executes addressed stop, not another proposal',()=>{const s=setup();act(s,'task','A');act(s,'run');const r=s.run;s.chatScope=s.selected;s.drafts[s.chatScope]='Останови агента';act(s,'send');s.drafts[s.chatScope]='Остановить запуск';act(s,'send');assert.equal(r.status,'stopping');assert.equal(s.messages[s.chatScope].filter(m=>m.command==='stop').length,1)})
test('action-specific acceptance never executes a different pending command',()=>{for(const reply of ['Добавить задачу','Добавить доработку','Принять результат']){const s=setup();act(s,'task','A');act(s,'run');const r=s.run;s.chatScope=s.selected;s.drafts[s.chatScope]='Останови агента';act(s,'send');s.drafts[s.chatScope]=reply;act(s,'send');assert.equal(r.status,'running');assert.equal(s.projects[0].tasks.length,1)}const {s,b,p}=proposal();send(s,b,'Принять результат');assert.equal(p.tasks.length,0);assert(!b.outcome.applied)})
