import test from 'node:test'
import assert from 'node:assert/strict'
import {projectGraphState,transitionGraphPlan,createGraphModel,renderGraph,graphRouteState,graphReturnHref,reduceGraphState,createGraphState} from '../product/graphs.mjs'
const fixtures={as_of:'fixture',projects:[{id:'orbit',name:'Orbit'}],tasks:[{id:'O1',project:'orbit',title:'Contract',state:'done'},{id:'O2',project:'orbit',title:'Implementation',state:'running'},{id:'O3',project:'orbit',title:'Check',state:'backlog'},{id:'AT-42',project:'atlas',title:'Foreign',state:'running'}],goals:[{id:'G1',project:'orbit',title:'Launch Orbit',revision:'goal-1',tasks:['O1','O2']},{id:'G2',project:'orbit',title:'Check Orbit',revision:'goal-1',tasks:[]}],taskLinks:[{project:'orbit',from:'O1',to:'O2',rel:'needs',payload:'Contract v1',source:'evidence-1'}],projectRuns:[{id:'orbit-run-1',project:'orbit',task:'O2',plan_version:'old-plan',state:'running'}]}
const opts={project:'orbit',fixtures,memberRole:'owner'},change=(state,a,extra={})=>transitionGraphPlan(state,a,{...opts,...extra}),add={type:'dependency',from:'O2',to:'O3',operation:'add',reason:'Independent check needs implementation'}
test('governance goal tasks project into graph, with exact membership and revision sources',()=>{const m=createGraphModel('plan',opts);assert.ok(m.nodes.some(n=>n.id==='G1'));assert.ok(m.edges.some(e=>e.from==='G1'&&e.to==='O2'));assert.equal(m.progress.total,2);assert.equal(m.progress.done,1);assert.ok(m.nodes.find(n=>n.id==='G1').href.includes('view-goals'));assert.ok(!m.nodes.some(n=>n.id==='AT-42'))})
test('dependency save changes rendered edge and keeps immutable baseline and run pins',()=>{const before=structuredClone(fixtures),s=change({},add),e=s.projects.orbit;assert.equal(e.revisions.length,1);assert.equal(e.revisions[0].reason,add.reason);assert.equal(e.baseline.relations.some(r=>r.from==='O2'&&r.to==='O3'),false);const m=createGraphModel('plan',{...opts,graphPlanEdits:s});assert.ok(m.edges.some(r=>r.from==='O2'&&r.to==='O3'));assert.deepEqual(fixtures,before);assert.equal(createGraphModel('history',{...opts,graphPlanEdits:s}).nodes.find(n=>n.id==='orbit-run-1').revision,'old-plan')})
test('cycle and self edges fail atomically without new version or fabricated graph links',()=>{let s=change({},add),before=structuredClone(s.projects.orbit.revisions);s=change(s,{...add,from:'O3',to:'O1'});assert.match(s.projects.orbit.error,/Цикл/);assert.deepEqual(s.projects.orbit.revisions,before);assert.equal(s.projects.orbit.sequence,1);s=change(s,{...add,from:'O2',to:'O2'});assert.match(s.projects.orbit.error,/сама/);assert.equal(s.projects.orbit.revisions.length,1)})
test('membership add/remove retains finished tasks in denominator and never double counts a shared task',()=>{let s=change({},{...add,type:'membership',from:'O3',to:'G1'});let m=createGraphModel('plan',{...opts,graphPlanEdits:s});assert.equal(m.progress.total,3);assert.equal(m.progress.done,1);s=change(s,{...add,type:'membership',from:'O1',to:'G2'});m=createGraphModel('plan',{...opts,graphPlanEdits:s});assert.equal(m.progress.total,3);s=change(s,{...add,type:'membership',from:'O3',to:'G1',operation:'remove'});assert.equal(createGraphModel('plan',{...opts,graphPlanEdits:s}).progress.total,2)})
test('duplicate, foreign object, missing reason and denied scopes cannot create new versions',()=>{for(const a of [{...add,from:'O1',to:'O2'},{...add,from:'AT-42'},{...add,reason:''}])assert.equal(change({},a).projects.orbit.sequence,0);for(const guard of [{read:'partial'},{read:'read-only'},{memberRole:'member'},{created:'true'}])assert.equal(change({},add,guard).projects.orbit.sequence,0)})
test('historical source/edited revisions keep old membership; URL returns exact plan revision',()=>{let s=change({},add);s=change(s,{...add,type:'membership',from:'O3',to:'G1'});const historical={planRevision:'fixture-plan-orbit-1'},m=createGraphModel('plan',{...opts,state:historical,graphPlanEdits:s});assert.equal(m.progress.total,2);assert.equal(createGraphModel('plan',{...opts,state:{planRevision:'source-baseline'},graphPlanEdits:s}).edges.some(r=>r.from==='O2'&&r.to==='O3'),false);const state=graphRouteState(graphReturnHref('plan',historical,'orbit'));assert.equal(state.planRevision,historical.planRevision);assert.equal(reduceGraphState(createGraphState(),{type:'planRevision',value:historical.planRevision},m).planRevision,historical.planRevision);assert.match(change(s,add,{planRevision:'source-baseline'}).projects.orbit.error,/Историческая/);assert.match(createGraphModel('plan',{...opts,state:{planRevision:'missing'},graphPlanEdits:s}).unavailable,/не прочитана/)})
test('external goal changes require explicit rebase and preserve older snapshots',()=>{const first=change({},add),newFixtures=structuredClone(fixtures);newFixtures.goals[0].title='Revised Orbit';newFixtures.goals[0].revision='goal-2';newFixtures.goals[0].tasks.push('O3');const m=createGraphModel('plan',{...opts,fixtures:newFixtures,graphPlanEdits:first});assert.ok(m.diagnostics.some(v=>v.includes('source')));assert.equal(m.nodes.find(n=>n.id==='G1').title,'Launch Orbit');const refused=change(first,{...add,type:'membership',from:'O3',to:'G2'},{fixtures:newFixtures});assert.match(refused.projects.orbit.error,/изменились/);const next=change(refused,{type:'rebase',reason:'Reviewed new governance goal'},{fixtures:newFixtures});assert.equal(next.projects.orbit.revisions.length,2);assert.equal(createGraphModel('plan',{...opts,fixtures:newFixtures,graphPlanEdits:next}).nodes.find(n=>n.id==='G1').title,'Revised Orbit');assert.equal(next.projects.orbit.revisions[0].goals[0].title,'Launch Orbit')})
test('current task completion reflects live state without changing plan relations or historical checkpoint',()=>{const s=change({},add),updated=structuredClone(fixtures);updated.tasks[1].state='done';assert.equal(createGraphModel('plan',{...opts,fixtures:updated,graphPlanEdits:s}).progress.done,2);assert.equal(createGraphModel('plan',{...opts,fixtures:updated,graphPlanEdits:s,state:{planRevision:'fixture-plan-orbit-1'}}).progress.done,1)})
test('plan store is cloned, scoped by project, and unsafe reason text remains inert in render',()=>{let s=change({}, {...add,reason:'<script>alert(1)</script>'});const before=structuredClone(s),copy=projectGraphState({graphPlanEdits:s});copy.projects.orbit.sequence=99;assert.deepEqual(s,before);const html=renderGraph('plan',{...opts,graphPlanEdits:s});assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>alert'));assert.equal(createGraphModel('plan',{...opts,project:'atlas',graphPlanEdits:s}).nodes.some(n=>n.id==='O3'),false)})
