import {moduleURL as inlineModule} from './lib/module-url.mjs'
import {fileURLToPath} from 'node:url'
import {readFileSync} from 'node:fs'
import assert from 'node:assert/strict'
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright')
const base=new URL('../../',import.meta.url),read=p=>readFileSync(new URL(p,base),'utf8'),asModule=text=>'data:text/javascript;base64,'+Buffer.from(text).toString('base64'),root=fileURLToPath(base),rURL=inlineModule('scripts/product/routines.mjs',root),oURL=inlineModule('scripts/product/obligations.mjs',root),wURL=inlineModule('scripts/product/workbench.mjs',root)
const css=read('apps/desktop/src/renderer/src/tokens.paperclip.css')+read('apps/desktop/src/renderer/src/tokens.passioncode.css')+read('apps/desktop/src/renderer/src/tokens.app.css')+`body{margin:0;padding:16px;background:var(--app-bg);color:var(--app-ink);font-family:var(--font-body)}main{max-width:1100px;margin:auto}*{box-sizing:border-box}.field{display:grid;gap:8px;margin:12px 0}.panel{padding:16px;border:1px solid var(--app-line);margin:16px 0;border-radius:8px}input,select,textarea{max-width:100%;min-width:0;font:inherit}.form-panel{max-width:100%}.table-wrap{overflow:auto}button,a{min-height:40px}.subnav{display:flex;flex-wrap:wrap}.code-block{white-space:pre-wrap;overflow-wrap:anywhere}table{border-collapse:collapse}td,th{padding:8px;vertical-align:top}p{overflow-wrap:anywhere}`
const browser=await chromium.launch({headless:true,...(process.env.FABRIC_CHROME?{executablePath:process.env.FABRIC_CHROME}:{})});let checks=0
try{const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent(`<html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}</style></head><body><main></main><script type="module">import * as w from '${wURL}';import * as r from '${rURL}';window.w=w;window.r=r;window.s={project:'atlas',cycle:'retro',state:'ready'};window.f={as_of:'fixture 09:42',projects:[{id:'atlas',name:'Atlas',lifecycle:'active'},{id:'orbit',name:'Orbit',lifecycle:'active'}],questions:[],events:[],tasks:[]};let records=r.routineStore('atlas').records;records.push({...structuredClone(records[0]),id:'RT-2',name:'По событию',trigger:'event',runs:[]});window.draw=()=>{let main=document.querySelector('main');const next=main.cloneNode(false);main.replaceWith(next);next.innerHTML=w.renderWorkbench('schedule',window.s,window.f);w.attachWorkbenchInteractions(next,{state:()=>window.s,fixtures:window.f,rerender:window.draw,navigate:()=>{}})};window.draw();window.ready=true;</script></body></html>`);await page.waitForFunction(()=>window.ready)
 const form=t=>page.locator(`[data-workbench-form="${t}"]`),act=t=>page.locator(`[data-workbench-action="${t}"]`).first(),submit=async t=>{await form(t).locator('button[type=submit]').click()}
 assert.match(await page.locator('main').innerText(),/Routines настроены.*тиков ещё нет/s);checks++
 await form('schedule-filter').locator('[name=type]').selectOption('event');await submit('schedule-filter');assert.match(await page.locator('main').innerText(),/RT-2/);assert.equal(await form('schedule').count(),0);assert.equal(await page.evaluate(()=>window.r.routineStore('atlas').records[0].runs.length),0);await act('schedule-clear-filters').click();checks++
 await act('cycle-wake').click();assert.equal(await page.evaluate(()=>window.r.sharedCycleState('atlas','retro').phase),'admitted');await act('cycle-wake').click();assert.equal(await page.evaluate(()=>window.r.sharedCycleState('atlas','retro').ticks.length),1);await act('cycle-inflight').click();await act('cycle-complete').click();assert.equal(await page.evaluate(()=>window.r.routineStore('atlas').records[0].runs.length),1);assert.equal(await page.locator('tbody tr').filter({hasText:'tick-retro-1'}).count(),1);checks++
 await form('schedule-filter').locator('[name=history]').selectOption('attention');await submit('schedule-filter');assert.match(await page.locator('[data-schedule-empty="history-filter"]').innerText(),/История существует/);await act('schedule-clear-filters').click();checks++
 await page.locator('summary').filter({hasText:'Независимые источники'}).click();await form('schedule-source').locator('[name=history]').selectOption('unavailable');await submit('schedule-source');assert.match(await page.locator('main').innerText(),/Нет подтверждённого результата чтения истории/);assert.equal(await act('cycle-wake').isDisabled(),true);assert.equal(await page.evaluate(()=>window.r.sharedCycleState('atlas','retro').ticks.length),1);checks++
 await page.locator('summary').filter({hasText:'Независимые источники'}).click();await form('schedule-source').locator('[name=history]').selectOption('ready');await form('schedule-source').locator('[name=routines]').selectOption('loading');await submit('schedule-source');assert.match(await page.locator('main').innerText(),/Чтение ещё выполняется/);assert.equal(await page.locator('tbody tr').filter({hasText:'tick-retro-1'}).count(),1);assert.equal(await form('schedule').count(),0);checks++
 await page.locator('summary').filter({hasText:'Независимые источники'}).click();await form('schedule-source').locator('[name=routines]').selectOption('ready');await form('schedule-source').locator('[name=host]').selectOption('stale');await submit('schedule-source');assert.equal(await act('cycle-wake').isDisabled(),true);checks++
 await page.locator('summary').filter({hasText:'Независимые источники'}).click();await form('schedule-source').locator('[name=host]').selectOption('ready');await submit('schedule-source');await page.locator('summary').filter({hasText:'Ветки допуска'}).click();await act('cycle-unknown').click();await act('cycle-wake').click();assert.equal(await page.evaluate(()=>window.r.sharedCycleState('atlas','retro').ticks.length),1);await act('cycle-reconcile').click();/* The window already holds tick-retro-1 (completed): reconciliation finds that receipt and admits nothing new (one tick per window). */assert.equal(await page.evaluate(()=>window.r.sharedCycleState('atlas','retro').phase),'ready');assert.match(await page.evaluate(()=>window.r.sharedCycleState('atlas','retro').reconciliation),/tick-retro-1/);const count=await page.evaluate(()=>window.r.sharedCycleState('atlas','retro').ticks.length);await act('cycle-wake').click();assert.equal(await page.evaluate(()=>window.r.sharedCycleState('atlas','retro').ticks.length),count);checks++
 await form('schedule').locator('[name=cadence]').fill('45');await submit('schedule');assert.equal(await page.evaluate(()=>window.r.sharedCycleState('atlas','retro').cadence),'45');assert.equal(await page.evaluate(()=>window.r.routineStore('atlas').records[0].runtime.cadence),'45');checks++
 await page.evaluate(()=>{window.r.routineStore('orbit').records=[];window.s.project='orbit';window.draw()});assert.match(await page.locator('[data-schedule-empty="routines"]').innerText(),/пока не настроены/);assert.equal(await page.evaluate(()=>window.r.routineStore('orbit').records.length),0);checks++
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks++
 assert.deepEqual(errors,[]);console.log(`Schedule semantic browser: ${checks} checks pass; page errors 0.`)
}finally{await browser.close()}
