// End-to-end fixture checks against the generated report, not a real provider.
const {chromium}=require(process.env.FABRIC_PLAYWRIGHT_MODULE||'playwright')
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict')
const root=path.resolve(__dirname,'../..')
const server=http.createServer((req,res)=>{res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(fs.readFileSync(path.join(root,'docs/reports/product.html')))})
let browser
;(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r))
 const localChrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
 browser=await chromium.launch({headless:true,...(fs.existsSync(localChrome)?{executablePath:localChrome}:{})})
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[]
 page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(8000)
 const base='http://127.0.0.1:'+server.address().port
 let pageCase=0
 const go=async(view,state='ready',project='atlas')=>{await page.goto(base+'/?case='+(++pageCase)+'#view-'+view+'?project='+project+'&state='+state);await page.locator('#product-screen h2').first().waitFor()}
 const screen=page.locator('#product-screen'),act=(id,account)=>screen.locator(`[data-accounts-action="${id}"]${account?`[data-account-id="${account}"]`:''}`).first()
 await go('provider-accounts');await act('default','b').click();assert.match(await screen.innerText(),/Текущие разговоры не переключены/)
 await screen.getByRole('link',{name:'Продолжить разговор Atlas',exact:true}).click();assert.equal(await screen.locator('[data-pa-current]').innerText(),'Рабочий')
 await screen.locator('[name="pa-draft"]').fill('Сохраните черновик — маяк-17');const history=await screen.getByRole('log').innerText()
 for(const expected of ['Резервный','Рабочий']){await act('prepare').click();await act('commit').click();assert.equal(await screen.locator('[data-pa-current]').innerText(),expected);assert.equal(await screen.getByRole('log').innerText(),history);assert.equal(await screen.locator('[name="pa-draft"]').inputValue(),'Сохраните черновик — маяк-17');assert.match(await screen.innerText(),/Другой разговор Atlas остаётся на аккаунте «Рабочий»/)}
 checks.push('Default affects future launches only; A→B→A retains fixture history/draft, increments run and keeps other binding')
 await go('account-switch','busy');await act('prepare').click();assert.match(await screen.innerText(),/Ждём сохранённой границы/);await act('cancel').click();assert.equal(await screen.locator('[data-pa-current]').innerText(),'Рабочий');assert.equal(await act('commit').count(),0)
 await act('prepare').click();await screen.getByText('Условие примера',{exact:true}).click();await act('boundary').click();await act('commit').click();assert.equal(await screen.locator('[data-pa-current]').innerText(),'Резервный');checks.push('Busy waits; cancel leaves A; only simulated certified boundary permits commit')
 await go('account-switch','resume-failed');await act('prepare').click();await act('commit').click();assert.match(await screen.innerText(),/Разговор сохранён, продолжение остановлено/);assert.equal(await screen.locator('[data-pa-current]').innerText(),'Рабочий');await act('restore').click();assert.match(await screen.innerText(),/прежний аккаунт и разговор подтверждены/);checks.push('Failed target resume does not report success; explicit restoration retains old account')
 await go('account-switch','unknown');await act('reconcile').click();await act('reconcile').click();assert.match(await screen.innerText(),/Результат остаётся неизвестным/);assert.equal(await act('commit').count(),0);checks.push('Unknown outcome remains unknown after repeated reconciliation; no switch button')
 await go('account-switch','unsupported');assert.equal(await act('prepare').count(),0);await screen.getByText('Отдельный новый разговор с переносом контекста',{exact:true}).click();assert.match(await screen.innerText(),/Новый разговор получит другую историю/)
 await go('account-switch','denied');assert.equal(await screen.locator('[name="pa-draft"]').count(),0);assert(!/work@example.com|маяк-17/.test(await screen.innerText()))
 await go('account-switch','ready','orbit');assert.match(await screen.innerText(),/не найден в этом проекте/);assert(!/work@example.com|маяк-17/.test(await screen.innerText()));checks.push('Unsupported native resume unavailable; denied and other project hide conversation/identity')
 await go('provider-accounts','empty');assert.match(await screen.innerText(),/Добавлять аккаунты необязательно/);await act('login').click();await act('login-cancel').click();assert.match(await screen.innerText(),/Вход отменён/)
 await act('login').click();await act('login-complete').click();assert.match(await screen.innerText(),/new@example.com/);await act('usage','b').click();assert.match(await screen.innerText(),/Данные другого аккаунта не подставлены/)
 await act('remove','a').click();assert.equal(await act('remove-confirm').count(),0);await act('remove-cancel').click();await act('remove','b').click();await act('remove-confirm','b').click();assert(!/spare@example.com/.test(await screen.innerText()));assert.match(await screen.innerText(),/История сохранена/)
 await act('runtime','remote').click();assert.match(await screen.innerText(),/Устройство недоступно/);assert.equal(await act('login').count(),0);checks.push('Optional system login, cancel/add fixture account, unknown usage, dependency-safe removal and offline runtime')
 await go('account-switch');await screen.getByText('Условия примера автопереключения',{exact:true}).click();await act('auto-tick').click();assert.equal(await screen.locator('[data-pa-current]').innerText(),'Рабочий')
 await act('auto-enable').click();await screen.locator('[name="pa-draft"]').fill('Автоматический переход сохраняет этот текст');const autoHistory=await screen.getByRole('log').innerText();await screen.getByText('Условия примера автопереключения',{exact:true}).click();await act('auto-tick').click();assert.equal(await screen.locator('[data-pa-current]').innerText(),'Резервный');assert.equal(await act('commit').count(),0);assert.match(await screen.innerText(),/без второго подтверждения/);assert.equal(await screen.getByRole('log').innerText(),autoHistory);assert.equal(await screen.locator('[name="pa-draft"]').inputValue(),'Автоматический переход сохраняет этот текст');await screen.getByText('Условия примера автопереключения',{exact:true}).click();await act('auto-tick').click();assert.equal(await screen.locator('[data-pa-current]').innerText(),'Резервный');assert.match(await screen.innerText(),/Повторного переключения нет/)
 checks.push('Auto is opt-in; enabled fixture crosses threshold and switches without confirmation; history/draft/other account retained and cooldown prevents ping-pong')
 await go('account-switch');await act('auto-exclude','b').click();await act('auto-enable').click();await screen.getByText('Условия примера автопереключения',{exact:true}).click();await act('auto-tick').click();assert.equal(await screen.locator('[data-pa-current]').innerText(),'Рабочий');assert.match(await screen.innerText(),/Нет разрешённого аккаунта/);await screen.getByText('Условия примера автопереключения',{exact:true}).click();await act('auto-unknown').click();assert.match(await screen.innerText(),/Квоты неизвестны/);checks.push('Excluded candidate and unknown quota hold auto without changing account')
 await go('account-switch','busy');await act('auto-enable').click();await screen.getByText('Условия примера автопереключения',{exact:true}).click();await act('auto-tick').click();assert.match(await screen.innerText(),/Ждём сохранённой границы/);await act('auto-pause').click();assert.equal(await act('boundary').count(),0);assert.equal(await screen.locator('[data-pa-current]').innerText(),'Рабочий');await act('auto-enable').click();await screen.getByText('Условия примера автопереключения',{exact:true}).click();await act('auto-tick').click();await screen.getByText('Условие примера',{exact:true}).click();await act('boundary').click();assert.equal(await screen.locator('[data-pa-current]').innerText(),'Резервный');assert.equal(await act('commit').count(),0);checks.push('Queued auto can be paused; certified boundary auto-continues without a confirmation screen')
 await go('account-switch','unsupported');assert.equal(await act('auto-enable').count(),0)
 await go('account-switch');await act('auto-enable').click();await screen.getByText('Условия примера автопереключения',{exact:true}).click();await act('auto-proactive').click();assert.equal(await screen.locator('[data-pa-current]').innerText(),'Рабочий');await screen.locator('[name="pa-auto-strategy"]').selectOption('consume-first');await screen.getByText('Условия примера автопереключения',{exact:true}).click();await act('auto-proactive').click();assert.equal(await screen.locator('[data-pa-current]').innerText(),'Резервный');checks.push('Before threshold, best stays while consume-first uses the eligible earlier-reset fixture account without confirmation')
 for(const view of ['provider-accounts','account-switch'])for(const width of [1440,375]){await page.setViewportSize({width,height:1000});await go(view);const size=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(size.scroll<=size.width+1,view+' overflow '+JSON.stringify(size))}
 checks.push('Both views at 1440px and 375px without document overflow')
 await page.setViewportSize({width:1440,height:1100});await go('provider-accounts');if(process.env.FABRIC_ACCOUNT_SCREENSHOTS){fs.mkdirSync(process.env.FABRIC_ACCOUNT_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.FABRIC_ACCOUNT_SCREENSHOTS,'accounts-desktop.png')});await go('account-switch');await page.screenshot({path:path.join(process.env.FABRIC_ACCOUNT_SCREENSHOTS,'switch-desktop.png')});await page.setViewportSize({width:375,height:1000});await page.screenshot({path:path.join(process.env.FABRIC_ACCOUNT_SCREENSHOTS,'switch-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1100});await page.locator('[data-action=toggle-theme]').click();await page.screenshot({path:path.join(process.env.FABRIC_ACCOUNT_SCREENSHOTS,'switch-light.png')});await screen.getByRole('heading',{name:'Автопереключение',exact:true}).locator('xpath=ancestor::section[1]').screenshot({path:path.join(process.env.FABRIC_ACCOUNT_SCREENSHOTS,'auto-controls.png')})}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'pass',scope:'Generated target report fixtures only; no CLI/native-resume validation',checks,errors},null,2))
 await browser.close();server.close()
})().catch(async error=>{console.error(error);if(browser)await browser.close();server.close();process.exitCode=1})
