import {readFileSync} from 'node:fs'
import assert from 'node:assert/strict'
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright')
const base=new URL('../../',import.meta.url),read=p=>readFileSync(new URL(p,base),'utf8'),moduleURL='data:text/javascript;base64,'+Buffer.from(read('scripts/product/graphs.mjs')).toString('base64'),css=['apps/desktop/src/renderer/src/tokens.paperclip.css','apps/desktop/src/renderer/src/tokens.passioncode.css','apps/desktop/src/renderer/src/tokens.app.css','scripts/product/graphs.css'].map(read).join('\n')
const fixtures={projects:[{id:'orbit',name:'Orbit'}],tasks:[{id:'O1',title:'Contract',project:'orbit',state:'done'},{id:'O2',title:'Build',project:'orbit',state:'running'},{id:'O3',title:'Check',project:'orbit',state:'backlog'}],goals:[{id:'G1',project:'orbit',title:'Ship Orbit',revision:'g1',tasks:['O1','O2']}],taskLinks:[{project:'orbit',from:'O1',to:'O2',rel:'needs',source:'f1'}],projectRuns:[{id:'r1',project:'orbit',task:'O2',plan_version:'pinned-old',state:'running'}]}
const browser=await chromium.launch({headless:true,...(process.env.FABRIC_CHROME?{executablePath:process.env.FABRIC_CHROME}:{})});let checks=0
try{const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent(`<html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}body{padding:16px;margin:0}main{max-width:1150px;margin:auto}</style></head><body><main></main><script type="module">import * as g from '${moduleURL}';window.g=g;window.f=${JSON.stringify(fixtures)};window.edits={};window.s={};window.draw=()=>{window.clean?.();document.querySelector('main').innerHTML=g.renderGraph('plan',{project:'orbit',fixtures:window.f,graphPlanEdits:window.edits,state:window.s});window.clean=g.attachGraphInteractions(document.querySelector('main'),{onStateChange:s=>window.s=s,onPlanChange:(edits,event)=>{window.edits=edits;window.last=event},onNavigate:(x,e)=>{e.preventDefault();window.nav=x}})};window.draw();window.ready=true;</script></body></html>`);await page.waitForFunction(()=>window.ready)
 const editor=page.locator('.fg-plan-editor'),form=page.locator('[data-graph-plan-form]'),set=async(type,from,to,operation='add')=>{await form.locator('[name=type]').selectOption(type);await form.locator('[name=from]').selectOption(from);await form.locator('[name=to]').selectOption(to);await form.locator('[name=operation]').selectOption(operation);await form.locator('[name=reason]').fill('Review exact dependency');await form.locator('button').click()}
 await editor.locator('summary').first().click();await set('dependency','O2','O3');assert.equal(await page.evaluate(()=>window.last.revision),'fixture-plan-orbit-1');assert.equal(await page.locator('[data-graph-value="edge:O2:needs:O3"]').count(),1);checks++
 await set('dependency','O3','O1');assert.match(await page.locator('.fg-plan-error').innerText(),/Цикл/);assert.equal(await page.evaluate(()=>window.edits.projects.orbit.revisions.length),1);assert.equal(await page.locator('[data-graph-value="edge:O3:needs:O1"]').count(),0);checks++
 await set('membership','O3','G1');assert.match(await page.locator('.fg-snapshot').innerText(),/1 \/ 3 задач/);await page.locator('[data-graph-control="planRevision"]').selectOption('source-baseline');assert.equal(await page.locator('[data-graph-value="edge:O2:needs:O3"]').count(),0);assert.equal(await form.locator('button').isDisabled(),true);assert.equal(await page.evaluate(()=>window.s.planRevision),'source-baseline');checks++
 await page.locator('[data-graph-control="planRevision"]').selectOption('fixture-plan-orbit-1');assert.match(await page.locator('.fg-snapshot').innerText(),/1 \/ 2 задач/);await page.locator('.fg-node[data-graph-value="node:O2"]').click();await page.locator('[data-graph-inspector] a').first().click();assert.ok((await page.evaluate(()=>window.nav.returnHref)).includes('graphPlanRevision=fixture-plan-orbit-1'));checks++
 await page.locator('[data-graph-control="planRevision"]').selectOption('');await page.evaluate(()=>{window.f.goals[0].title='New governance title';window.f.goals[0].revision='g2';window.draw()});assert.equal(await form.locator('button').isDisabled(),true);assert.ok(await page.locator('[data-graph-plan-rebase]').count());await page.locator('[data-graph-plan-rebase] button').click();assert.equal(await page.evaluate(()=>window.edits.projects.orbit.revisions.length),3);assert.match(await page.locator('.fg-node[data-graph-value="node:G1"]').innerText(),/New governance title/);assert.equal(await page.evaluate(()=>window.f.projectRuns[0].plan_version),'pinned-old');checks++
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await editor.evaluate(e=>getComputedStyle(e).animationName),'none');checks++
 if(process.env.GRAPH_PLAN_SCREENSHOT)await page.screenshot({path:process.env.GRAPH_PLAN_SCREENSHOT,fullPage:true})
 assert.deepEqual(errors,[]);console.log(`Graph plan browser: ${checks} checks pass; page errors 0.`)
}finally{await browser.close()}
