import {moduleURL as inlineModule} from './lib/module-url.mjs'
import {fileURLToPath} from 'node:url'
// Optional real-browser fixture tests; requires locally installed Playwright.
import {readFileSync} from 'node:fs'
import assert from 'node:assert/strict'
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const base=new URL('../../',import.meta.url),read=p=>readFileSync(new URL(p,base),'utf8')
const moduleURL=inlineModule('scripts/product/integrations.mjs',fileURLToPath(new URL('../../',import.meta.url)))
const css=['apps/desktop/src/renderer/src/tokens.paperclip.css','apps/desktop/src/renderer/src/tokens.passioncode.css','apps/desktop/src/renderer/src/tokens.app.css','scripts/product/integrations.css'].map(read).join('\n')
const browser=await chromium.launch({headless:true,...(process.env.FABRIC_CHROME?{executablePath:process.env.FABRIC_CHROME}:{})});let checks=0
try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.setContent(`<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}body{margin:0;padding:16px}main{max-width:1080px;margin:auto}</style></head><body><main></main><script type="module">import * as m from '${moduleURL}';window.m=m;window.s={project:'atlas',provider:'codex',roleSlot:'reviewer',providerRevision:'demo-2',state:'ready'};window.view='admission';window.go=(view,patch={})=>{window.view=view;Object.assign(window.s,patch);window.draw()};window.draw=()=>{window.integrationCleanup?.();document.querySelector('main').innerHTML=m.renderIntegrations(window.view,window.s,{});window.integrationCleanup=m.attachIntegrationsInteractions(document.querySelector('main'),{state:()=>window.s,navigate:window.go,rerender:window.draw})};window.draw();window.ready=true;</script></body></html>`)
 await page.waitForFunction(()=>window.ready)
 const action=(type)=>page.locator(`[data-integrations-action="${type}"]`).first(),form=type=>page.locator(`[data-integrations-form="${type}"]`)
 await action('local-check').click();await page.locator('[data-integrations-action="independent-check"]').first().click();assert.equal(await action('admit').isDisabled(),true);checks++
 await page.locator('[data-integrations-action="independent-check"]').last().click();await action('admit').click();await form('bind').locator('[name="budget"]').fill('7');await form('bind').locator('button').click();await page.locator('[data-integrations-action="canary"]').last().click();let data=await page.evaluate(()=>window.s.integrations.bindings);assert.equal(data['atlas:reviewer'].budget,7);assert.equal(data['atlas:reviewer'].status,'ready');assert.equal(data['atlas:product-manager'],undefined);checks++
 await page.locator('a').filter({hasText:'Проверить следующую ревизию'}).click();assert.equal(await action('admit').isDisabled(),true);checks++
 await page.evaluate(()=>window.go('bootstrap'));await form('recipe').locator('[name="consumer"]').fill('Custom consumer');await form('recipe').locator('[name="transport"]').selectOption('a2a');await form('recipe').locator('button[type=submit]').click();assert.equal(await page.evaluate(()=>window.s.integrations.recipe.transport),'a2a');assert.equal(await page.evaluate(()=>window.s.integrations.recipe.consumer),'Custom consumer');checks++
 await form('recipe').locator('[name="integrity"]').selectOption('fail');await form('recipe').locator('button[type=submit]').click();assert.equal(await page.evaluate(()=>window.s.integrations.recipe),null);assert.equal(await form('recipe').locator('[name="consumer"]').inputValue(),'Custom consumer');checks++
 await page.evaluate(()=>window.go('connect-account'));await form('connection-review').locator('[name="resources"][value="atlas-app"]').uncheck();await form('connection-review').locator('[name="resources"][value="orbit-api"]').check();await form('connection-review').locator('[name="agents"][value="builder"]').uncheck();await form('connection-review').locator('[name="agents"][value="reviewer"]').check();await form('connection-review').locator('button').click();await page.locator('[data-integrations-action="connection-callback"]').nth(1).click();assert.equal(await action('connection-save').isDisabled(),true);checks++
 await page.locator('[data-integrations-action="connection-callback"]').first().click();await action('connection-save').click();assert.deepEqual(await page.evaluate(()=>window.s.integrations.connections.atlas.resources),['orbit-api']);assert.deepEqual(await page.evaluate(()=>window.s.integrations.connections.atlas.agents),['reviewer']);checks++
 await page.evaluate(()=>window.go('access-detail',{access:'new'}));await form('access-save').locator('[name="name"]').fill('Browser custom access');await form('access-save').locator('button').click();assert.match(await page.locator('main').innerText(),/DEMO-NOT-A-CREDENTIAL/);await page.locator('a').filter({hasText:'К списку доступов'}).click();assert.match(await page.locator('main').innerText(),/Закрыть однократный показ/);await action('leave-reveal').click();assert.equal(await page.evaluate(()=>window.s.integrations.reveal),null);checks++
 await page.evaluate(()=>window.go('authority',{effect:'staging',answer:'committed',answerChoice:'allow'}));await action('grant').click();await action('reserve').click();await page.locator('[data-integrations-action="dispatch"]').first().click();assert.equal(await action('reserve').isDisabled(),true);assert.equal(await page.locator('[data-integrations-action="dispatch"]').last().isDisabled(),true);await action('reconcile-effect').click();assert.equal(await page.evaluate(()=>window.s.integrations.grants['effect-staging-01'].status),'spent');checks++
 await page.evaluate(()=>window.go('membership'));await form('invite-prepare').locator('[name="email"]').fill('invited@example.invalid');await form('invite-prepare').locator('button').click();let id=await page.evaluate(()=>window.s.invite);assert.equal(await action('invite-accept').isDisabled(),true);await form('invite-signin').locator('[name="identity"]').fill('wrong@example.invalid');await form('invite-signin').locator('button').click();assert.equal(await action('invite-accept').isDisabled(),true);await form('invite-signin').locator('[name="identity"]').fill('invited@example.invalid');await form('invite-signin').locator('button').click();await action('invite-accept').click();await action('invite-accept').click();assert.equal(await page.evaluate(()=>window.s.integrations.members.length),1);assert.equal(await page.evaluate(id=>window.s.integrations.invitations[id].role,id),'member');checks++
 await page.evaluate(()=>window.go('role-workspace',{memberRole:'member'}));assert.equal(await page.locator('a').filter({hasText:'Изменить host layout'}).count(),0);assert.match(await page.locator('a').filter({hasText:'Открыть точную задачу AT-47'}).getAttribute('href'),/task=AT-47/);await form('interaction').locator('textarea').fill('The revoked invitation is denied');await form('interaction').locator('[name="effect"]').selectOption('publish');await form('interaction').locator('button').click();assert.match(await page.locator('.ig-error').innerText(),/grant/);assert.equal(await form('interaction').locator('textarea').inputValue(),'The revoked invitation is denied');checks++
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await form('interaction').evaluate(e=>getComputedStyle(e).animationName),'none');checks++
 await page.evaluate(()=>window.go('access-detail',{access:'external-coordinator',memberRole:'owner',state:'partial'}));assert.equal(await form('access-save').locator('button').isDisabled(),true);assert.equal(await page.locator('.ig-error').count(),0);checks++
 if(process.env.INTEGRATIONS_SCREENSHOT)await page.screenshot({path:process.env.INTEGRATIONS_SCREENSHOT,fullPage:true})
 assert.deepEqual(errors,[]);console.log(`Integrations browser behavior: ${checks} checks passed; page errors: ${errors.length}.`)
}finally{await browser.close()}
