import {moduleURL as inlineModule} from './lib/module-url.mjs'
import {fileURLToPath} from 'node:url'
import {readFileSync} from 'node:fs'
import assert from 'node:assert/strict'
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright')
const base=new URL('../../',import.meta.url),read=p=>readFileSync(new URL(p,base),'utf8'),moduleURL=inlineModule('scripts/product/integrations.mjs',fileURLToPath(new URL('../../',import.meta.url))),css=['apps/desktop/src/renderer/src/tokens.paperclip.css','apps/desktop/src/renderer/src/tokens.passioncode.css','apps/desktop/src/renderer/src/tokens.app.css','scripts/product/integrations.css'].map(read).join('\n')
const browser=await chromium.launch({headless:true,...(process.env.FABRIC_CHROME?{executablePath:process.env.FABRIC_CHROME}:{})});let checks=0
try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.setContent(`<html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}body{margin:0;padding:16px}main{max-width:1080px;margin:auto}</style></head><body><main></main><script type="module">import * as m from '${moduleURL}';window.m=m;window.s={project:'atlas',provider:'codex',roleSlot:'reviewer',providerRevision:'demo-2',state:'ready'};window.view='admission';window.go=(view,patch={})=>{window.view=view;Object.assign(window.s,patch);window.draw()};window.draw=()=>{window.cleanup?.();document.querySelector('main').innerHTML=m.renderIntegrations(window.view,window.s,{});window.cleanup=m.attachIntegrationsInteractions(document.querySelector('main'),{state:()=>window.s,navigate:window.go,rerender:window.draw})};window.draw();window.ready=true;</script></body></html>`);await page.waitForFunction(()=>window.ready)
 const action=t=>page.locator(`[data-integrations-action="${t}"]`).first(),form=t=>page.locator(`[data-integrations-form="${t}"]`),submit=async t=>{await form(t).locator('button[type=submit]').click()}
 await action('local-check').click();for(const name of ['shape','protocol','semantic'])await page.locator('[data-integrations-action="gate-check"]').filter({hasText:name+': pass'}).click();assert.equal(await action('admit').isDisabled(),true);await page.locator('[data-integrations-action="gate-check"]').filter({hasText:'effects: failure'}).click();assert.equal(await action('admit').isDisabled(),true);await page.locator('[data-integrations-action="gate-check"]').filter({hasText:'effects: pass'}).click();await action('admit').click();assert.equal(await page.evaluate(()=>Object.keys(window.s.integrations.admissions['codex@demo-2'].gates).length),4);checks++
 await page.evaluate(()=>window.go('bootstrap'));await submit('recipe');await submit('local-report');let oldRecipe=await page.evaluate(()=>window.s.integrations.recipe.id);await action('report-to-gate').click();assert.equal(await page.evaluate(()=>window.view),'admission');assert.equal(await page.evaluate(()=>window.s.integrations.admissions['codex@demo-2'].localSource.recipe),oldRecipe);assert.equal(await action('admit').isDisabled(),true);checks++
 await page.evaluate(()=>window.go('bootstrap'));await action('recipe-expire').click();assert.equal(await action('copy-recipe').isDisabled(),true);assert.equal(await form('local-report').locator('button').isDisabled(),true);await action('recipe-reissue').click();assert.equal(await page.evaluate(()=>window.s.integrations.recipe.reissuedFrom),oldRecipe);assert.equal(await action('copy-recipe').isDisabled(),false);await action('report-to-gate').click();assert.match(await page.locator('.ig-error').innerText(),/exact recipe/);checks++
 await submit('recipe-cleanup-preview');assert.equal(await page.evaluate(()=>window.s.integrations.cleanupDiff.length),3);await action('recipe-cleanup-apply').click();assert.equal(await page.evaluate(()=>Object.keys(window.s.integrations.recipeFiles).length),1);await page.locator('summary').filter({hasText:'Cleanup receipt'}).click();assert.match(await page.locator('main').innerText(),/preserved/);checks++
 await page.evaluate(()=>window.go('connect-account'));await submit('connection-review');await page.locator('[data-integrations-action="connection-callback"]').filter({hasText:'Исход неизвестен'}).click();const operation=await page.evaluate(()=>window.s.integrations.connectionReview.operationId);await action('connection-reconcile').click();await action('connection-save').click();const revision=await page.evaluate(()=>window.s.integrations.connections.atlas.revision);await page.locator('[data-integrations-action="connection-callback"]').first().click();await action('connection-save').click();assert.equal(await page.evaluate(()=>window.s.integrations.connections.atlas.revision),revision);assert.equal(await page.evaluate(()=>window.s.integrations.connectionReview.operationId),operation);checks++
 await page.evaluate(()=>window.go('access'));await form('access-filter').locator('[name=status]').selectOption('revoked');await submit('access-filter');assert.match(await page.locator('main').innerText(),/Review agent/);assert.doesNotMatch(await page.locator('main').innerText(),/External coordinator/);await form('access-filter').locator('[name=scope]').selectOption('orbit');await submit('access-filter');assert.match(await page.locator('main').innerText(),/нет доступов/);checks++
 await page.evaluate(()=>window.go('role-workspace',{interaction:'review-AT47'}));await form('interaction').locator('textarea').fill('I have different evidence, keep my draft');await action('interaction-concurrent').click();assert.equal(await form('interaction').locator('textarea').inputValue(),'I have different evidence, keep my draft');const receipt=await page.evaluate(()=>window.s.integrations.interactionResults['review-AT47'].receipt);await submit('interaction');assert.match(await page.locator('.ig-error').innerText(),/другой версии/);assert.equal(await page.evaluate(()=>window.s.integrations.interactionResults['review-AT47'].receipt),receipt);await action('interaction-followup').click();assert.equal(await page.evaluate(()=>window.s.integrations.followupDraft.submitted),false);assert.equal(await page.evaluate(()=>window.s.integrations.followupDraft.body),'I have different evidence, keep my draft');checks++
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks++
 assert.deepEqual(errors,[]);console.log(`Final integration browser: ${checks} checks pass; page errors 0.`)
}finally{await browser.close()}
