// Independent end-to-end acceptance against the root-generated report. No product IO.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process')
const {chromium}=require(process.env.FABRIC_PLAYWRIGHT_MODULE||'playwright')
const root=process.env.FABRIC_ROOT_SOURCE||path.resolve(__dirname,'../..'),base=process.env.FABRIC_REPORT_BASE||'http://127.0.0.1:8770/reports/product.html',out=process.env.FABRIC_WORKBENCH_RECEIPT||path.join(require('node:os').tmpdir(),'fabric-workbench-browser.json')
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),files=['scripts/product/controller.js','scripts/product/workbench.mjs','scripts/product/routines.mjs','scripts/product/new-project.mjs','scripts/product/guided.mjs','scripts/product/guided.css','scripts/product/governance.mjs','scripts/product/integrations.mjs','scripts/product/operations.mjs'],snap=()=>Object.fromEntries(files.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))
;(async()=>{
 const body=await fetch(base).then(r=>{assert.equal(r.status,200);return r.text()}),receipt={suite:'independent-root-workbench/v1',at:new Date().toISOString(),root_commit:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),base,served_sha256:sha(body),source_sha256:snap(),scope:'Prototype fixture behavior only. Real DB/providers/processes/OAuth untouched.',checks:[],page_errors:[]}
 const browser=await chromium.launch({headless:true,...(process.env.FABRIC_CHROME?{executablePath:process.env.FABRIC_CHROME}:{})}),page=await browser.newPage({viewport:{width:1440,height:1000}}),screen=page.locator('#product-screen');page.setDefaultTimeout(3500);page.on('pageerror',e=>receipt.page_errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(new URL(base).origin+'/')?r.continue():r.abort())
 const creationActions={'new-project-draft':'another','cancel-project-draft':'cancel','discard-project-draft':'discard','project-refused':'refused','project-unknown':'unknown','reconcile-project':'reconcile','confirm-create-project':'create','save-draft':'save'}
 let reload=0;const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))),fresh=async hash=>{await page.goto(base+'?workbench-test='+ ++reload+hash);await page.waitForFunction(()=>document.documentElement.classList.contains('js'));await settle()},move=async hash=>{await page.evaluate(h=>location.hash=h,hash);await settle()},expand=async()=>{await screen.locator('details').evaluateAll(es=>es.forEach(e=>e.open=true))},act=(kind,id)=>screen.locator(`[data-${kind}-action="${id}"]`).first(),rootAct=id=>screen.locator(creationActions[id]?`[data-guide="${creationActions[id]}"]`:`[data-action="${id}"]`).first(),form=(kind,id)=>screen.locator(`[data-${kind}-form="${id}"]`),submit=async(kind,id)=>{await form(kind,id).evaluate(f=>f.requestSubmit());await settle()},draftField=(name)=>screen.locator(`[data-guide-field="${name}"]`),countProjects=()=>page.evaluate(()=>fixtures.projects.length),routine=()=>page.evaluate(()=>structuredClone(routineStore('atlas').records.find(r=>r.id==='RT-1')))
 const guideAct=id=>screen.locator(`[data-guide="${id}"]`).first()
 const draftSnapshot=()=>page.evaluate(()=>structuredClone(creationDrafts.get((state.estate||'team-estate')+'|'+state.draftId)))
 async function startIdea(){await screen.locator('[data-guide=mode][data-mode=idea]').click();await guideAct('next').click();await settle();assert.equal(await draftField('name').isVisible(),true)}
 async function reviewCreationUI(){await guideAct('next').click();await settle();assert.equal(await guideAct('create').isVisible(),true)}
 async function openCreatedProject(){await page.waitForURL(/view-launch-guide/);const id=await page.evaluate(()=>state.project);await screen.getByRole('link',{name:'Открыть проект',exact:true}).click();await page.waitForURL(/view-launch-project/);assert.equal(await page.evaluate(()=>state.project),id);return id}
 async function check(name,fn){try{const evidence=await fn();receipt.checks.push({name,status:'pass',evidence:evidence||null})}catch(e){const failure={name,status:'fail',error:e.message,route:page.url(),screen:(await screen.innerText().catch(()=>'')),state:await page.evaluate(()=>({project:state.project,draftId:state.draftId,draft:state.draft,creation:creationDrafts.get((state.estate||'team-estate')+'|'+state.draftId),routines:typeof routineStore==='function'?routineStore('atlas'):null})).catch(()=>null)};receipt.checks.push(failure);console.error('FAIL',name,e.message)}fs.writeFileSync(out,JSON.stringify(receipt,null,2))}
 async function seedSoftware(){await fresh('#view-estate?project=atlas');const id=await page.evaluate(()=>commitProjectDraft({name:'Boreal verified',purpose:'Own verified startup result',starter:'software',stages:['Define contract','Verify boundary','Release with receipt'],repoMode:'none'}).id);await move('#view-project?project='+id);return id}
 // Removed 2026-09-28 (CO-171): four G04 checks, the G05 software-preview check and AD03 drove the guided creation
  // form via #view-onboarding / launch-start, which renderFirstRelease pre-empts (first-release routing, FLW-55), so
  // no operator reaches it. Their semantics are the 18 pure tests in scripts/test/adoption-creation.test.mjs, run by ci.sh.
  await check('G05 PM activation requires exact project role binding and checked canary',async()=>{
  const id=await seedSoftware();assert.equal(await rootAct('activate-pm').isDisabled(),true)
  await move('#view-admission?project='+id+'&provider=fabric&providerRevision=demo-2&roleSlot=builder');await act('integrations','local-check').click();await screen.locator('[data-integrations-action="independent-check"]').filter({hasText:'pass'}).click();await act('integrations','admit').click();await submit('integrations','bind');await screen.locator('[data-integrations-action="canary"]').filter({hasText:'pass'}).click();await move('#view-project?project='+id);assert.equal(await rootAct('activate-pm').isDisabled(),true);assert.equal(await page.evaluate(id=>!!fixtures.projects.find(p=>p.id===id).pmActive,id),false)
  await move('#view-admission?project=atlas&provider=fabric&providerRevision=demo-2&roleSlot=product-manager');await submit('integrations','bind');await screen.locator('[data-integrations-action="canary"]').filter({hasText:'pass'}).click();await move('#view-project?project='+id);assert.equal(await rootAct('activate-pm').isDisabled(),true);assert.equal(await page.evaluate(id=>Boolean(fixtures.projects.find(p=>p.id===id).pmBinding),id),false)
  await move('#view-admission?project='+id+'&provider=fabric&providerRevision=demo-2&roleSlot=product-manager');await submit('integrations','bind');await move('#view-project?project='+id);assert.equal(await rootAct('activate-pm').isDisabled(),true);await move('#view-admission?project='+id+'&provider=fabric&providerRevision=demo-2&roleSlot=product-manager');await screen.locator('[data-integrations-action="canary"]').filter({hasText:'pass'}).click();await move('#view-project?project='+id);assert.equal(await rootAct('activate-pm').isDisabled(),false);await rootAct('activate-pm').click();const p=await page.evaluate(id=>structuredClone(fixtures.projects.find(p=>p.id===id)),id);assert.equal(p.pmActive,true);assert.equal(p.pmBinding.project,id);assert.equal(p.pmBinding.role,'product-manager');assert.equal(p.pmReceipt,'pm-activation:'+id+':'+p.pmBinding.revision);assert.equal(await rootAct('activate-pm').isDisabled(),true);return {project:id,binding:p.pmBinding,receipt:p.pmReceipt}
 })
 await check('G54 cycles manual admission / ACK / completion and next-window dedup',async()=>{
  await fresh('#view-cycles?project=atlas&cycle=retro');await act('workbench','cycle-wake').click();let r=await routine();assert.equal(r.runtime.phase,'admitted');assert.equal(r.runs.length,1);assert.equal(r.runs[0].outcome,'admitted');await act('workbench','cycle-wake').click();assert.equal((await routine()).runs.length,1);await expand();await act('workbench','cycle-next-window').click();assert.equal((await routine()).runtime.manualWindow,'window-0');await act('workbench','cycle-inflight').click();await act('workbench','cycle-complete').click();r=await routine();assert.equal(r.runs[0].outcome,'completed');await expand();await act('workbench','cycle-next-window').click();await act('workbench','cycle-wake').click();r=await routine();assert.equal(r.runs.length,2);assert.notEqual(r.runs[0].window,r.runs[1].window);assert.equal(r.runs[0].outcome,'completed');assert.equal(r.runs[1].outcome,'admitted');return {runs:r.runs}
 })
 await check('G54 admitted old run keeps provider/version when routine revised for future window',async()=>{
  await fresh('#view-cycles?project=atlas&cycle=retro');await act('workbench','cycle-wake').click();const old=(await routine()).runs[0];await move('#view-routine-editor?project=atlas&routine=RT-1');await expand();await screen.locator('[name=provider]').selectOption('codex');await screen.locator('[name=reason]').fill('Future binding only');await submit('routine','edit');await act('routine','commit').click();assert.equal((await routine()).revision,2);await move('#view-cycles?project=atlas&cycle=retro');await act('workbench','cycle-inflight').click();await act('workbench','cycle-complete').click();let r=await routine();assert.equal(r.runs[0].revision,old.revision);assert.equal(r.runs[0].provider,old.provider);await expand();await act('workbench','cycle-next-window').click();await act('workbench','cycle-wake').click();r=await routine();assert.equal(r.runs.at(-1).revision,2);assert.equal(r.runs.at(-1).provider,'codex');return {old:r.runs[0],next:r.runs.at(-1)}
 })
 await check('G55 unready binding cannot resume; fresh readiness restores next admission',async()=>{
  await fresh('#view-cycles?project=atlas&cycle=retro');await expand();await act('workbench','cycle-unready').click();await act('workbench','cycle-resume').click();let r=await routine();assert.equal(r.state,'paused');assert.equal(r.runtime.bindingReady,false);assert.equal(r.runtime.phase,'unready');const count=r.runs.length;await act('workbench','cycle-wake').click();r=await routine();assert.equal(r.runs.at(-1).outcome,'refused');assert.equal(r.runs.length,count+1);await expand();await act('workbench','cycle-ready').click();await act('workbench','cycle-resume').click();await act('workbench','cycle-wake').click();r=await routine();assert.equal(r.runtime.phase,'admitted');assert.equal(r.state,'active')
 })
 await check('G55 independent source failure holds mutation and paused state, recovery retains history',async()=>{
  await fresh('#view-schedule?project=atlas&cycle=retro');await act('workbench','cycle-wake').click();const saved=await routine();await expand();await form('workbench','schedule-source').locator('[name=host]').selectOption('unavailable');await submit('workbench','schedule-source');assert.equal(await act('workbench','cycle-resume').isDisabled(),true);assert.equal(await act('workbench','cycle-wake').isDisabled(),true);assert.deepEqual((await routine()).runs,saved.runs);assert.equal((await routine()).state,'paused');await expand();await form('workbench','schedule-source').locator('[name=host]').selectOption('ready');await form('workbench','schedule-source').locator('[name=history]').selectOption('unavailable');await submit('workbench','schedule-source');assert.match(await screen.innerText(),/Нет подтверждённого результата чтения истории/);assert.deepEqual((await routine()).runs,saved.runs);await expand();await form('workbench','schedule-source').locator('[name=history]').selectOption('ready');await submit('workbench','schedule-source');assert.equal(await act('workbench','cycle-inflight').isDisabled(),false);await act('workbench','cycle-inflight').click();await act('workbench','cycle-complete').click();assert.equal((await routine()).runs[0].outcome,'completed')
 })
 await check('G54 unknown same-window reconcile cannot invent a second known admission',async()=>{
  await fresh('#view-cycles?project=atlas&cycle=retro');await act('workbench','cycle-wake').click();const old=(await routine()).runs[0];await expand();await act('workbench','cycle-unknown').click();await act('workbench','cycle-wake').click();assert.equal((await routine()).runs.length,1);await act('workbench','cycle-reconcile').click();const r=await routine();assert.equal(r.runs.length,1,'reconciliation duplicated already known admission');assert.equal(r.runs[0].id,old.id)
 })
 const configure=async values=>{await expand();for(const [name,value]of Object.entries(values))await screen.locator(`[name="${name}"]`).selectOption(value);await screen.locator('[name=reason]').fill('Independent policy case '+JSON.stringify(values));await submit('routine','edit');await act('routine','commit').click()}
 for(const [payload,choices]of Object.entries({missing:['block','skip'],empty:['skip','run','block'],stale:['refresh','block','allow']}))for(const edge of [0,1])for(const policy of choices){
  await check(`SRC06 edge ${edge} ${payload}=${policy} applies to full run and keeps upstream states`,async()=>{
   await fresh('#view-routine-editor?project=atlas&routine=RT-1');const values={[payload+'-'+edge]:policy};if(edge===1)values[payload+'-0']=payload==='missing'?'skip':payload==='empty'?'run':'allow';await configure(values);await act('routine','toggle').click();await screen.locator('[name=routine-payload]').selectOption(payload);await act('routine','tick').click();const r=await routine(),run=r.runs.at(-1),expected=policy==='block'?'blocked':policy==='skip'?'skipped':policy==='refresh'?'awaiting-fresh-source':'done';assert.equal(run.steps[0].status,'done');if(edge===1&&payload==='missing'){assert.equal(run.steps[1].status,'skipped');assert.equal(run.steps[2].status,'pending');return {blockedByUpstream:true,policyConfigured:r.edges[edge][payload],run}}assert.equal(run.steps[edge+1].status,expected);assert.equal(run.revision,2);assert.equal(run.steps.length,3);if(edge===0&&expected!=='done')assert.equal(run.steps[2].status,'pending');return {run}
  })
 }
 for(const [policy,count]of [['latest',1],['all',3],['none',0]])await check('SRC06 catch-up '+policy+' produces '+count+' full fresh runs',async()=>{
  await fresh('#view-routine-editor?project=atlas&routine=RT-1');await configure({catchup:policy});await act('routine','toggle').click();await act('routine','catchup').click();let r=await routine();assert.equal(r.runs.length,count);assert.ok(r.runs.every(x=>x.steps.length===3&&x.steps.every(s=>s.status==='done')));if(count){const old=r.runs.length;await act('routine','replay').click();assert.equal((await routine()).runs.length,old)}return {policy,actualRuns:r.runs.length}
 })
 await check('SRC06 failed first input stops bounded series without a false boundary proposal',async()=>{
  await fresh('#view-routine-editor?project=atlas&routine=RT-1');await act('routine','toggle').click();await screen.locator('[name=routine-payload]').selectOption('missing');const before=await page.evaluate(()=>({proposals:fixtures.proposals.length,observations:fixtures.observations.length}));await act('routine','bound').click();const r=await routine();assert.equal(r.runs.length,1);assert.equal(r.runs[0].outcome,'blocked');assert.deepEqual(r.runs[0].steps.map(s=>s.status),['done','blocked','pending']);assert.equal(await page.evaluate(()=>fixtures.proposals.length),before.proposals);assert.equal(await page.evaluate(()=>fixtures.observations.length),before.observations);assert.equal(await page.evaluate(()=>fixtures.proposals.some(p=>p.id.startsWith('RT-1-proposal-'))),false);return {stopped:r.runs[0].id,createdBoundaryProposal:false}
 })
 await check('SRC06 bounded full runs create exact observation and resolvable PM proposal with replay dedup',async()=>{
  await fresh('#view-routine-editor?project=atlas&routine=RT-1');await act('routine','toggle').click();await act('routine','bound').click();const r=await routine();assert.equal(r.runs.length,r.bound);assert.ok(r.runs.every(x=>x.steps.every(s=>s.status==='done')));const p=await page.evaluate(()=>structuredClone(fixtures.proposals.find(p=>p.id.startsWith('RT-1-proposal-'))));assert.ok(p);const observed=await page.evaluate(p=>fixtures.observations.find(o=>o.project===p.sourceProject&&o.id===p.sourceIds[0]),p);assert.ok(observed);assert.deepEqual(p.snapshot,observed);assert.equal(observed.id,r.runs.at(-1).id);await move('#view-cross-project-proposal?project=atlas&proposal='+p.id);assert.match(await screen.innerText(),new RegExp(p.id));assert.doesNotMatch(await screen.innerText(),/Предложение недоступно/);await screen.locator('[name=proposal-reason]').fill('Complete bounded result reviewed independently');const before=await page.evaluate(()=>fixtures.tasks.length);await submit('governance','proposal');assert.equal(await page.evaluate(()=>fixtures.tasks.length),before);await act('governance','proposal-confirm').click();const resolved=await page.evaluate(id=>structuredClone(fixtures.proposals.find(p=>p.id===id)),p.id);assert.equal(resolved.status,'accepted');assert.equal(await page.evaluate(()=>fixtures.tasks.length),before+1);await act('governance','proposal-replay').click();assert.equal(await page.evaluate(()=>fixtures.tasks.length),before+1);await screen.locator('[data-governance-route=task]').click();await settle();assert.match(await screen.innerText(),new RegExp(resolved.task));return {proposal:p.id,source:observed.id,decision:resolved.decision,task:resolved.task}
 })
 await check('workbench surfaces remain usable at 390px',async()=>{await page.setViewportSize({width:390,height:844});for(const view of ['onboarding','schedule','routine-editor']){await fresh('#view-'+view+'?project=atlas');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,view+' overflow');}return {width:390}})
 receipt.served_sha256_after=sha(await fetch(base).then(r=>r.text()));receipt.served_changed=receipt.served_sha256!==receipt.served_sha256_after;receipt.source_sha256_after=snap();receipt.sources_changed=files.filter(f=>receipt.source_sha256[f]!==receipt.source_sha256_after[f]);receipt.status=receipt.checks.some(c=>c.status==='fail')||receipt.page_errors.length?'fail':'pass';receipt.totals={pass:receipt.checks.filter(c=>c.status==='pass').length,fail:receipt.checks.filter(c=>c.status==='fail').length};fs.writeFileSync(out,JSON.stringify(receipt,null,2));console.log(JSON.stringify({status:receipt.status,...receipt.totals,page_errors:receipt.page_errors,sources_changed:receipt.sources_changed,served_changed:receipt.served_changed,receipt:out}));await browser.close();if(receipt.status!=='pass')process.exitCode=1
})().catch(e=>{console.error(e);process.exitCode=1})
