import {moduleURL as inlineModule} from './lib/module-url.mjs'
import {fileURLToPath} from 'node:url'
// Optional real-browser verification of source-driven fixture interactions.
import {readFileSync} from 'node:fs'
import assert from 'node:assert/strict'
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright')
const base=new URL('../../',import.meta.url),read=p=>readFileSync(new URL(p,base),'utf8')
const moduleURL=inlineModule('scripts/product/integrations.mjs',fileURLToPath(new URL('../../',import.meta.url)))
const css=['apps/desktop/src/renderer/src/tokens.paperclip.css','apps/desktop/src/renderer/src/tokens.passioncode.css','apps/desktop/src/renderer/src/tokens.app.css','scripts/product/integrations.css'].map(read).join('\n')
const browser=await chromium.launch({headless:true,...(process.env.FABRIC_CHROME?{executablePath:process.env.FABRIC_CHROME}:{})});let checks=0
try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.setContent(`<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}body{margin:0;padding:16px}main{max-width:1080px;margin:auto}</style></head><body><main></main><script type="module">import * as m from '${moduleURL}';window.m=m;window.s={project:'atlas',estate:'team-estate',provider:'codex',roleSlot:'reviewer',providerRevision:'demo-2',state:'ready'};window.view='membership';window.go=(view,patch={})=>{window.view=view;Object.assign(window.s,patch);window.draw()};window.draw=()=>{window.integrationCleanup?.();document.querySelector('main').innerHTML=m.renderIntegrations(window.view,window.s,{});window.integrationCleanup=m.attachIntegrationsInteractions(document.querySelector('main'),{state:()=>window.s,navigate:window.go,rerender:window.draw})};window.draw();window.ready=true;</script></body></html>`)
 await page.waitForFunction(()=>window.ready)
 const action=t=>page.locator(`[data-integrations-action="${t}"]`).first(),form=t=>page.locator(`[data-integrations-form="${t}"]`),submit=async t=>{await form(t).locator('button').click()}
 await page.locator('[data-integrations-action="estate-switch"]').last().click();assert.equal(await page.evaluate(()=>window.s.estate),'personal-estate');assert.equal(await page.evaluate(()=>window.s.project),'');assert.equal(await form('invite-prepare').count(),0);checks++
 await page.locator('[data-integrations-action="estate-switch"]').first().click();await form('estate-actor').locator('select').selectOption('demo-coowner');await submit('estate-actor');assert.equal(await page.evaluate(()=>window.s.memberRole),'owner');checks++
 await form('estate-actor').locator('select').selectOption('demo-owner');await submit('estate-actor');await page.evaluate(()=>window.go('role-workspace',{project:'atlas',interaction:'review-AT47'}))
 await form('delegation-prepare').locator('[name="point"]').selectOption('approve-publication');await submit('delegation-prepare');assert.match(await page.locator('.ig-error').innerText(),/требует человека/);assert.equal(await form('delegation-resolve').count(),0);checks++
 await form('delegation-prepare').locator('[name="point"]').selectOption('respond-review');await submit('delegation-prepare');assert.equal(await action('delegation-canary').isDisabled(),true);await action('delegation-admission').click();await action('delegation-canary').click();await submit('delegation-resolve');assert.match(await page.locator('.ig-error').innerText(),/checker/);checks++
 await form('delegation-resolve').locator('[name="checker"]').selectOption('passed');await submit('delegation-resolve');assert.equal(await page.evaluate(()=>window.s.integrations.sourceDemos.pointResults['respond-review'].actor),'demo-owner');assert.equal(await form('delegation-resolve').locator('button').isDisabled(),true);checks++
 await page.evaluate(()=>{const id=window.m.seedAgentConfiguration(window.s,{kind:'agent-config',title:'CEO named reviewer',prompt:'Check exact invitation return',project:'atlas',source:'ceo-thread-7',id:'artifact-7'});window.go('providers',{agentConfig:id})});assert.equal(await form('config-save').locator('[name="prompt"]').inputValue(),'Check exact invitation return');await form('config-save').locator('[name="consumer"]').fill('Atlas / reviewer routine');await submit('config-save');assert.equal(await page.evaluate(()=>window.s.integrations.sourceDemos.configs[window.s.agentConfig].revision),1);checks++
 await form('config-canary').locator('[name="outcome"]').selectOption('pass');await submit('config-canary');assert.match(await page.locator('.ig-error').innerText(),/не допущена/);checks++
 await page.evaluate(()=>window.go('admission',{provider:'codex',providerRevision:'demo-2'}));await action('local-check').click();await page.locator('[data-integrations-action="independent-check"]').last().click();await action('admit').click();await submit('bind');await page.locator('[data-integrations-action="canary"]').last().click()
 await form('provider-promote').locator('[name="evalSet"]').selectOption('zero');await submit('provider-promote');assert.match(await page.locator('.ig-error').innerText(),/Ноль отказов/);await form('provider-promote').locator('[name="evalSet"]').selectOption('mixed');await submit('provider-promote');assert.equal(await page.evaluate(()=>window.s.integrations.sourceDemos.promotions.length),1);checks++
 await form('quality-select').locator('select').selectOption('zero');await submit('quality-select');assert.match(await page.locator('main').innerText(),/0 rejected runs \/ 3 runs/);assert.equal(await page.evaluate(()=>window.s.qualitySet),'zero');await form('quality-select').locator('select').selectOption('unavailable');await submit('quality-select');assert.match(await page.locator('main').innerText(),/0 rejected runs \/ 0 runs/);checks++
 await page.evaluate(()=>window.go('providers'));await form('config-canary').locator('[name="outcome"]').selectOption('pass');await submit('config-canary');await form('config-save').locator('[name="prompt"]').fill('Second prompt revision');await form('config-save').locator('[name="reason"]').fill('Need explicit references');await submit('config-save');assert.equal(await page.evaluate(()=>window.s.integrations.sourceDemos.configs[window.s.agentConfig].canary),'not-run');checks++
 await page.evaluate(()=>window.go('connections'));await form('collector-config').locator('input').fill('5');await submit('collector-config');assert.match(await page.locator('main').innerText(),/Stale по текущей cadence/);await action('collector-start').click();await page.locator('[data-integrations-action="collector-complete"]').nth(2).click();assert.equal(await page.evaluate(()=>window.s.integrations.sourceDemos.collectors.atlas.snapshots.length),1);assert.match(await page.locator('main').innerText(),/Источник не ответил/);checks++
 await action('collector-start').click();await page.locator('[data-integrations-action="collector-complete"]').nth(1).click();assert.equal(await page.evaluate(()=>window.s.integrations.sourceDemos.collectors.atlas.snapshots.at(-1).observations.length),0);await form('collector-select').locator('select').selectOption('snapshot-atlas-01');await submit('collector-select');await submit('collector-pin');assert.equal(await page.evaluate(()=>window.s.integrations.sourceDemos.collectors.atlas.pins.at(-1).snapshot),'snapshot-atlas-01');assert.equal(await page.evaluate(()=>window.s.integrations.sourceDemos.collectors.atlas.pins.at(-1).interpretation),null);checks++
 await action('collector-start').click();await page.locator('[data-integrations-action="collector-complete"]').last().click();await action('collector-start').click();assert.match(await page.locator('.ig-error').innerText(),/Retry-after/);await action('collector-clock').click();await action('collector-start').click();assert.equal(await page.evaluate(()=>window.s.integrations.sourceDemos.collectors.atlas.status),'processing');checks++
 await page.evaluate(()=>window.go('connect-account'));await submit('connection-review');await page.locator('[data-integrations-action="connection-callback"]').last().click();assert.equal(await action('connection-save').isDisabled(),true);await page.locator('[data-integrations-action="connection-callback"]').first().click();assert.match(await page.locator('.ig-error').innerText(),/истёк/);await submit('connection-review');await page.locator('[data-integrations-action="connection-callback"]').first().click();await action('connection-save').click();assert.equal(await page.evaluate(()=>window.s.integrations.connections.atlas.revision),4);checks++
 await page.evaluate(()=>window.go('connections'))
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await form('collector-config').evaluate(e=>getComputedStyle(e).animationName),'none');checks++
 if(process.env.INTEGRATION_SOURCES_SCREENSHOT)await page.screenshot({path:process.env.INTEGRATION_SOURCES_SCREENSHOT,fullPage:true})
 assert.deepEqual(errors,[]);console.log(`Integration source browser behavior: ${checks} checks passed; page errors: ${errors.length}.`)
}finally{await browser.close()}
