import {readFileSync} from 'node:fs'
import assert from 'node:assert/strict'
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const root=new URL('../../',import.meta.url),read=p=>readFileSync(new URL(p,root),'utf8'),f=JSON.parse(read('docs/ux/product-fixtures.json'))
f.agents=f.agents.map(a=>({...a,project:f.projects.find(p=>p.name===a.scope)?.id,binding:'binding-'+a.id+'-1'}))
f.projectRuns=[{id:'OR-18-run-1',iteration:1,task:'OR-18',project:'orbit',agent:'orbit-builder',binding:'binding-orbit-builder-1',phase:'running',plan_version:'orbit-v1',steps:[{id:'or-step',title:'Проверить доставку',status:'pending'}]},{id:'AT-47-run-1',iteration:1,task:'AT-47',project:'atlas',agent:'reviewer',binding:'binding-reviewer-1',phase:'admitted',plan_version:'review-v1'}]
const dataURL='data:text/javascript;base64,'+Buffer.from(read('scripts/product/graphs.mjs')).toString('base64'),css=['apps/desktop/src/renderer/src/tokens.paperclip.css','apps/desktop/src/renderer/src/tokens.passioncode.css','apps/desktop/src/renderer/src/tokens.app.css','scripts/product/graphs.css'].map(read).join('\n')
const browser=await chromium.launch({headless:true,...(process.env.FABRIC_CHROME?{executablePath:process.env.FABRIC_CHROME}:{})})
try{const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent(`<html><head><style>${css}</style></head><body><main></main><script type="module">import * as g from '${dataURL}';window.g=g;window.f=${JSON.stringify(f)};window.draw=(project,agent)=>{window.clean?.();document.querySelector('main').innerHTML=g.renderGraph('agent',{id:'scope-test',project,agent,fixtures:window.f});window.clean=g.attachGraphInteractions(document.querySelector('main'),{onNavigate:(x,e)=>{e.preventDefault();window.nav=x}})};window.draw('orbit','orbit-builder');window.ready=true;</script></body></html>`);await page.waitForFunction(()=>window.ready)
 const graph=page.locator('.fg-explorer');await graph.locator('.fg-node[data-graph-value="node:OR-18-run-1"]').click();assert.match(await graph.locator('[data-graph-inspector]').innerText(),/orbit-v1/);await graph.locator('[data-graph-inspector] a').filter({hasText:'К прогону 1'}).click();let nav=await page.evaluate(()=>window.nav);assert.ok(nav.href.includes('project=orbit'));assert.ok(nav.href.includes('run=OR-18-run-1'));assert.ok(nav.returnHref.includes('agent=orbit-builder'))
 await page.evaluate(()=>window.draw('atlas','reviewer'));assert.equal(await graph.locator('.fg-node[data-graph-value="node:AT-42"]').count(),0);await graph.locator('[data-graph-control="runId"]').selectOption('AT-47-run-1');assert.equal(await graph.locator('.fg-node[data-graph-value="node:AT-47-run-1"]').count(),1);await graph.locator('.fg-node[data-graph-value="node:AT-47-run-1"]').click();assert.match(await graph.locator('[data-graph-inspector]').innerText(),/План шагов не передан/);await graph.locator('[data-graph-inspector] a').filter({hasText:'К прогону 1'}).click();nav=await page.evaluate(()=>window.nav);assert.ok(nav.href.includes('task=AT-47'));assert.ok(nav.href.includes('agent=reviewer'));assert.ok(nav.returnHref.includes('graphTaskRun=AT-47-run-1'))
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('Graph scoped browser: Orbit and Reviewer identities, exact TaskRun selection/links/back, unknown steps, 390px: pass; page errors 0.')
}finally{await browser.close()}
