const {chromium}=require(process.env.FABRIC_PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),os=require('os');let ownedBrowser;
const output=process.env.FABRIC_BROWSER_OUTPUT||fs.mkdtempSync(path.join(os.tmpdir(),'fabric-system-browser-'));fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=ownedBrowser=await chromium.launch({headless:true,...(process.env.FABRIC_CHROME?{executablePath:process.env.FABRIC_CHROME}:{})});const result={scope:'isolated documentation browser, not native Fabric or live DB',checks:[]};
 for(const width of [1440,390]){
 const page=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce',colorScheme:width===1440?'dark':'light'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:8770/')?r.continue():r.abort());
 for(const anchor of ['system','entity-task_run','cycle-launch','cycle-step-answer-commit','task-M188','task-M152-continue','order-task-M173','ADR-0047']){
  await page.goto('http://127.0.0.1:8770/reports/system.html#'+anchor);await page.evaluate(()=>new Promise(requestAnimationFrame));
  const check=await page.evaluate(id=>{const target=document.getElementById(id);const ids=Array.from(document.querySelectorAll('[id]')).map(e=>e.id);const dup=ids.filter((x,i)=>ids.indexOf(x)!==i);return {anchor:id,width:innerWidth,documentWidth:document.documentElement.scrollWidth,targetExists:!!target,targetVisible:!!target&&!!target.getClientRects().length,view:document.querySelector('section[data-view]:not([hidden])')?.id,duplicates:dup,taskOpen:id.startsWith('task-')?target?.open:null,cycleSelection:document.querySelector('#cycle-picker [aria-pressed=true]')?.dataset.cycle};},anchor);
  result.checks.push({...check,errors:[...errors]});
  if(width===1440&&['system','cycle-launch','order-task-M173'].includes(anchor))await page.screenshot({path:path.join(output,'fabric-system-'+anchor+'.png')});
  if(width===390&&anchor==='entity-task_run')await page.screenshot({path:path.join(output,'fabric-system-mobile.png')});
 }
 await page.goto('http://127.0.0.1:8770/reports/system.html#tasks');const allCards=await page.locator('#task-list>.task:visible').count();if(allCards<1)throw Error('no task cards');await page.getByLabel('Найти задачу').fill('M188');const filtered=await page.locator('#task-list>.task:visible').count();if(filtered<1)throw Error('search lost M188');await page.getByLabel('Найти задачу').fill('no-match-!definitely');if(!(await page.locator('#no-tasks').isVisible()))throw Error('empty search missing');await page.getByRole('button',{name:'Сбросить фильтры'}).click();/* compared with the unfiltered count, not a literal that goes stale with every new card */if(await page.locator('#task-list>.task:visible').count()!==allCards)throw Error('reset lost cards');result.checks.push({width,filter_reset:true});
 await page.goto('http://127.0.0.1:8770/reports/system.html#data');await page.locator('#entity-picker').selectOption('grant_reservation');if(!(await page.locator('#entity-detail').innerText()).includes('GrantReservation'))throw Error('entity navigation stale');await page.locator('#data-diagram a').first().press('Enter');await page.waitForFunction(()=>location.hash.startsWith('#entity-'));await page.getByRole('link',{name:'Циклы',exact:true}).click();result.checks.push({width,entity_selection:true});await page.close();
 }
 const nojs=await browser.newPage({javaScriptEnabled:false});await nojs.goto('http://127.0.0.1:8770/reports/system.html');if(await nojs.locator('section[data-view]:visible').count()!==6)throw Error('No-JS fallback missing');result.checks.push({no_js_sections:6});await browser.close();
 const fail=result.checks.filter(x=>x.documentWidth>x.width||x.duplicates?.length||x.errors?.length||x.targetExists===false||x.taskOpen===false||(x.anchor==='cycle-step-answer-commit'&&x.cycleSelection!=='answer'));result.result=fail.length?'fail':'pass';fs.writeFileSync(path.join(output,'browser-check.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));if(fail.length)process.exitCode=1;
})().catch(async e=>{console.error(e);if(ownedBrowser)await ownedBrowser.close();process.exitCode=1});
